### ISSUE TITLE
bump flexbox to newest version

### ISSUE THREAD

**Issue by mahibi** [nextcloud/talk-android#1035]
bumping from 1.1.0 to 2.0.1. would lead to this error so the app won't start:

```
I/org.webrtc.Logging: NativeLibrary: Loading library: jingle_peerconnection_so
E/org.webrtc.Logging: NativeLibrary: Failed to load native library: jingle_peerconnection_so
    NativeLibrary: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.nextcloud.talk2.debug--NbCySMa_b3nkDjfp5Rf9w==/base.apk"],nativeLibraryDirectories=[/data/app/com.nextcloud.talk2.debug--NbCySMa_b3nkDjfp5Rf9w==/lib/x86, /data/app/com.nextcloud.talk2.debug--NbCySMa_b3nkDjfp5Rf9w==/base.apk!/lib/x86, /system/lib, /system/product/lib]]] couldn't find "libjingle_peerconnection_so.so"
E/org.webrtc.Logging: NativeLibrary: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.nextcloud.talk2.debug--NbCySMa_b3nkDjfp5Rf9w==/base.apk"],nativeLibraryDirectories=[/data/app/com.nextcloud.talk2.debug--NbCySMa_b3nkDjfp5Rf9w==/lib/x86, /data/app/com.nextcloud.talk2.debug--NbCySMa_b3nkDjfp5Rf9w==/base.apk!/lib/x86, /system/lib, /system/product/lib]]] couldn't find "libjingle_peerconnection_so.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1667)
        at org.webrtc.NativeLibrary$DefaultLoader.load(NativeLibrary.java:21)
        at org.webrtc.NativeLibrary.initialize(NativeLibrary.java:44)
        at org.webrtc.PeerConnectionFactory.initialize(PeerConnectionFactory.java:294)
        at com.nextcloud.talk.application.NextcloudTalkApplication.initializeWebRtc(NextcloudTalkApplication.kt:108)
        at com.nextcloud.talk.application.NextcloudTalkApplication.onCreate(NextcloudTalkApplication.kt:128)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1182)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6460)
        at android.app.ActivityThread.access$1300(ActivityThread.java:219)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/oud.talk2.debu: No implementation found for void org.webrtc.PeerConnectionFactory.nativeInitializeAndroidGlobals() (tried Java_org_webrtc_PeerConnectionFactory_nativeInitializeAndroidGlobals and Java_org_webrtc_PeerConnectionFactory_nativeInitializeAndroidGlobals__)
W/NextcloudTalkApplication: java.lang.UnsatisfiedLinkError: No implementation found for void org.webrtc.PeerConnectionFactory.nativeInitializeAndroidGlobals() (tried Java_org_webrtc_PeerConnectionFactory_nativeInitializeAndroidGlobals and Java_org_webrtc_PeerConnectionFactory_nativeInitializeAndroidGlobals__)
        at org.webrtc.PeerConnectionFactory.nativeInitializeAndroidGlobals(Native Method)
        at org.webrtc.PeerConnectionFactory.initialize(PeerConnectionFactory.java:295)
        at com.nextcloud.talk.application.NextcloudTalkApplication.initializeWebRtc(NextcloudTalkApplication.kt:108)
        at com.nextcloud.talk.application.NextcloudTalkApplication.onCreate(NextcloudTalkApplication.kt:128)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1182)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6460)
        at android.app.ActivityThread.access$1300(ActivityThread.java:219)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
I/dav4android: Registering DAV property factories
D/NetworkSecurityConfig: Using Network Security Config from resource network_security_config debugBuild: true
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.nextcloud.talk2.debug, PID: 17246
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.nextcloud.talk2.debug--NbCySMa_b3nkDjfp5Rf9w==/base.apk"],nativeLibraryDirectories=[/data/app/com.nextcloud.talk2.debug--NbCySMa_b3nkDjfp5Rf9w==/lib/x86, /data/app/com.nextcloud.talk2.debug--NbCySMa_b3nkDjfp5Rf9w==/base.apk!/lib/x86, /system/lib, /system/product/lib]]] couldn't find "libsqlcipher.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1667)
        at net.sqlcipher.database.SQLiteDatabase$1.loadLibraries(SQLiteDatabase.java:213)
        at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:230)
        at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:209)
        at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:202)
        at io.requery.android.sqlcipher.SqlCipherDatabaseSource.<init>(SqlCipherDatabaseSource.java:66)
        at com.nextcloud.talk.dagger.modules.DatabaseModule.provideSqlCipherDatabaseSource(DatabaseModule.java:49)
        at com.nextcloud.talk.dagger.modules.DatabaseModule_ProvideSqlCipherDatabaseSourceFactory.provideSqlCipherDatabaseSource(DatabaseModule_ProvideSqlCipherDatabaseSourceFactory.java:41)
        at com.nextcloud.talk.dagger.modules.DatabaseModule_ProvideSqlCipherDatabaseSourceFactory.get(DatabaseModule_ProvideSqlCipherDatabaseSourceFactory.java:31)
        at com.nextcloud.talk.dagger.modules.DatabaseModule_ProvideSqlCipherDatabaseSourceFactory.get(DatabaseModule_ProvideSqlCipherDatabaseSourceFactory.java:10)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at com.nextcloud.talk.dagger.modules.DatabaseModule_ProvideDataStoreFactory.get(DatabaseModule_ProvideDataStoreFactory.java:32)
        at com.nextcloud.talk.dagger.modules.DatabaseModule_ProvideDataStoreFactory.get(DatabaseModule_ProvideDataStoreFactory.java:11)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at com.nextcloud.talk.utils.database.user.UserModule_ProvideUserUtilsFactory.get(UserModule_ProvideUserUtilsFactory.java:31)
        at com.nextcloud.talk.utils.database.user.UserModule_ProvideUserUtilsFactory.get(UserModule_ProvideUserUtilsFactory.java:10)
        at com.nextcloud.talk.dagger.modules.RestModule_ProvideKeyManagerFactory.get(RestModule_ProvideKeyManagerFactory.java:35)
        at com.nextcloud.talk.dagger.modules.RestModule_ProvideKeyManagerFactory.get(RestModule_ProvideKeyManagerFactory.java:11)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at com.nextcloud.talk.dagger.modules.RestModule_ProvideSslSocketFactoryCompatFactory.get(RestModule_ProvideSslSocketFactoryCompatFactory.java:36)
        at com.nextcloud.talk.dagger.modules.RestModule_ProvideSslSocketFactoryCompatFactory.get(RestModule_ProvideSslSocketFactoryCompatFactory.java:11)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at com.nextcloud.talk.dagger.modules.RestModule_ProvideHttpClientFactory.get(RestModule_ProvideHttpClientFactory.java:59)
        at com.nextcloud.talk.dagger.modules.RestModule_ProvideHttpClientFactory.get(RestModule_ProvideHttpClientFactory.java:16)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at com.nextcloud.talk.application.DaggerNextcloudTalkApplicationComponent.injectNextcloudTalkApplication(DaggerNextcloudTalkApplicationComponent.java:591)
        at com.nextcloud.talk.application.DaggerNextcloudTalkApplicationComponent.inject(DaggerNextcloudTalkApplicationComponent.java:313)
        at com.nextcloud.talk.application.NextcloudTalkApplication.onCreate(NextcloudTalkApplication.kt:133)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1182)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6460)
        at android.app.ActivityThread.access$1300(ActivityThread.java:219)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
Disconnected from the target VM, address: 'localhost:42927', transport: 'socket'
```

**Comment by nickvergessen** [comment]
Done in #1211
