### ISSUE TITLE
App crashs when pressing on participants of a conversation

### ISSUE THREAD

**Issue by dorpauli** [nextcloud/talk-android#1314]
## Steps to reproduce
1. Navigate to a group conversation
2. Navigate to the conversation settings
3. Press on a random participant (also yourself) and see the app crashing immediately 

### Expected behaviour
I don*t know, but not crashing. Maybe show information about that person?

### Actual behaviour
The app is crashing and closes immediately 

## Device information

**Device:** Oneplus 7T

**Android version:** LineageOs 18.1 latest nightly

**Talk version:** 12.0.0 Alpha 15

## Server information

**Nextcloud version:** 21.0.2

**Talk version:** 11.2.2

**Custom Signaling server configured:** no

**Custom TURN server configured:** no

**Custom STUN server configured:** no
### Server log (data/nextcloud.log)
Nothing about this

**Comment by dorpauli** [comment]
I can still repoduce it with Version **12.1.0 RC1**.

**Comment by AndyScherzinger** [comment]
@dorpauli could you provide the error log as in the logcat / stack trace please? ❤️

**Comment by dorpauli** [comment]
I don't know about such a log. I think it's a development tool? I don't have a development environment.

Or could i get such a log with adb? Do you have a guide to get this log? 

And can't you reproduce the crash?

**Comment by jakobroehrl** [comment]
Can't reproduce it on my Oneplus 7T.
Maybe removing and reinstall the app helps?

**Comment by AndyScherzinger** [comment]
> And can't you reproduce the crash?

I can't :( - I guess it is because I don't have an account with the matching permissions, so I can't execute any actions on the participants list.

> Or could i get such a log with adb? Do you have a guide to get this log?

Yes, adb would work, here is a description (for the files app, not the talk app; but it should work anyways)
https://github.com/nextcloud/android#getting-debug-info-via-logcat-mag

**Comment by AndyScherzinger** [comment]
I think the string you'd use for the grep would be ```com.nextcloud.talk2```

**Comment by AndyScherzinger** [comment]
@nickvergessen can you reproduce this issue and maybe post a log?

**Comment by dorpauli** [comment]
```
06-24 14:32:38.131 19612 19612 D AndroidRuntime: Shutting down VM
06-24 14:32:38.132 19612 19612 E AndroidRuntime: FATAL EXCEPTION: main
06-24 14:32:38.132 19612 19612 E AndroidRuntime: Process: com.nextcloud.talk2, PID: 19612
06-24 14:32:38.132 19612 19612 E AndroidRuntime: java.lang.NullPointerException: participant.attendeePin must not be null
06-24 14:32:38.132 19612 19612 E AndroidRuntime: 	at com.nextcloud.talk.controllers.ConversationInfoController.onItemClick(ConversationInfoController.kt:858)
06-24 14:32:38.132 19612 19612 E AndroidRuntime: 	at eu.davidea.viewholders.FlexibleViewHolder.onClick(FlexibleViewHolder.java:122)
06-24 14:32:38.132 19612 19612 E AndroidRuntime: 	at android.view.View.performClick(View.java:7448)
06-24 14:32:38.132 19612 19612 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:7425)
06-24 14:32:38.132 19612 19612 E AndroidRuntime: 	at android.view.View.access$3600(View.java:810)
06-24 14:32:38.132 19612 19612 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:28305)
06-24 14:32:38.132 19612 19612 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
06-24 14:32:38.132 19612 19612 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
06-24 14:32:38.132 19612 19612 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
06-24 14:32:38.132 19612 19612 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7664)
06-24 14:32:38.132 19612 19612 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-24 14:32:38.132 19612 19612 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
06-24 14:32:38.132 19612 19612 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```

**Comment by dorpauli** [comment]
Is this helpful? I just started logcat and reproduced the crash afterwards.  This is the output i can assign to nextcloud talk.

**Comment by AndyScherzinger** [comment]
> Is this helpful?

Yes, absolutely! 👍 

Thanks, while I can't say what the root cause of this is I can at least say it is the log of the actual crash you described 👍

**Comment by dorpauli** [comment]
I could grep more log entries around the crash now. 

```
06-24 14:32:10.612 19612 22957 D SoLoader: Loaded: libimagepipeline.so
06-24 14:32:10.616 19612 22933 D SoLoader: About to load: libnative-imagetranscoder.so
06-24 14:32:10.617 19612 22933 D SoLoader: libnative-imagetranscoder.so not found on /data/user/0/com.nextcloud.talk2/lib-main
06-24 14:32:10.617 19612 22933 D SoLoader: libnative-imagetranscoder.so found on /data/app/~~jVAgRcZ6Dnz_h5idOaOFLA==/com.nextcloud.talk2-WU8rPufXpeL_Fu6wU8xWIA==/lib/arm64
06-24 14:32:10.617 19612 22933 D SoLoader: Not resolving dependencies for libnative-imagetranscoder.so
06-24 14:32:10.618 19612 22933 D SoLoader: Loaded: libnative-imagetranscoder.so
06-24 14:32:13.426 19612 19612 W unknown:WrappingUtils: Don't know how to round that drawable: android.graphics.drawable.VectorDrawable@faef976
06-24 14:32:13.454 19612 19612 D ChatController: Initialize TalkMessagesListAdapter with senderId: users/Paul
06-24 14:32:13.486 19612 22902 I nextcloud.talk: Waiting for a blocking GC ProfileSaver
06-24 14:32:13.495 19612 22902 I nextcloud.talk: WaitForGcToComplete blocked ProfileSaver on RunEmptyCheckpoint for 8.767ms
06-24 14:32:15.015 19612 19612 W unknown:WrappingUtils: Don't know how to round that drawable: android.graphics.drawable.VectorDrawable@b9f96f0
06-24 14:32:17.189 19612 22917 D OpenGLRenderer: endAllActiveAnimators on 0x7b1b4b3440 (MenuPopupWindow$MenuDropDownListView) with handle 0x7a3b485eb0
06-24 14:32:17.363 19612 19612 W unknown:WrappingUtils: Don't know how to round that drawable: android.graphics.drawable.VectorDrawable@7806ea3
06-24 14:32:38.131 19612 19612 D AndroidRuntime: Shutting down VM
06-24 14:32:38.132 19612 19612 E AndroidRuntime: FATAL EXCEPTION: main
06-24 14:32:38.132 19612 19612 E AndroidRuntime: Process: com.nextcloud.talk2, PID: 19612
06-24 14:32:38.132 19612 19612 E AndroidRuntime: java.lang.NullPointerException: participant.attendeePin must not be null
06-24 14:32:38.132 19612 19612 E AndroidRuntime: 	at com.nextcloud.talk.controllers.ConversationInfoController.onItemClick(ConversationInfoController.kt:858)
06-24 14:32:38.132 19612 19612 E AndroidRuntime: 	at eu.davidea.viewholders.FlexibleViewHolder.onClick(FlexibleViewHolder.java:122)
06-24 14:32:38.132 19612 19612 E AndroidRuntime: 	at android.view.View.performClick(View.java:7448)
06-24 14:32:38.132 19612 19612 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:7425)
06-24 14:32:38.132 19612 19612 E AndroidRuntime: 	at android.view.View.access$3600(View.java:810)
06-24 14:32:38.132 19612 19612 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:28305)
06-24 14:32:38.132 19612 19612 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
06-24 14:32:38.132 19612 19612 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
06-24 14:32:38.132 19612 19612 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
06-24 14:32:38.132 19612 19612 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7664)
06-24 14:32:38.132 19612 19612 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-24 14:32:38.132 19612 19612 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
06-24 14:32:38.132 19612 19612 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
06-24 14:32:43.395  1122 23059 I ActivityManager: Crashing app skipping ANR: ProcessRecord{651c0 19612:com.n
```

**Comment by AndyScherzinger** [comment]
@dorpauli can you check (install(test) https://github.com/nextcloud/talk-android/pull/1359#issuecomment-867635580 which contains a fix and installs a separate QA (Quality Assurance) build of the app?

**Comment by dorpauli** [comment]
I have. Now the crash don't happen, if i press on myself. But if i press on other participants, it still crashes.

I logged it again, but the log contains a lot private information. (i took the new app name,)
This are the latest entries and the only one bug related i think (older logs happened 10 secs before):
```
06-24 15:51:49.140 22967 22967 D AndroidRuntime: Shutting down VM
06-24 15:51:49.143 22967 22967 E AndroidRuntime: FATAL EXCEPTION: main
06-24 15:51:49.143 22967 22967 E AndroidRuntime: Process: com.nextcloud.talk2.qa, PID: 22967
06-24 15:51:49.143 22967 22967 E AndroidRuntime: java.lang.NullPointerException: participant.attendeePin must not be null
06-24 15:51:49.143 22967 22967 E AndroidRuntime: 	at com.nextcloud.talk.controllers.ConversationInfoController.onItemClick(ConversationI
```

**Comment by AndyScherzinger** [comment]
Hmm, the last line of your log is the important one put has been cur off :( - Can you reproduce it? There should be a line info at the end of that log-line.

**Comment by dorpauli** [comment]
```
06-24 16:36:46.886  2774  2774 D AndroidRuntime: Shutting down VM
06-24 16:36:46.888  2774  2774 E AndroidRuntime: FATAL EXCEPTION: main
06-24 16:36:46.888  2774  2774 E AndroidRuntime: Process: com.nextcloud.talk2.qa, PID: 2774
06-24 16:36:46.888  2774  2774 E AndroidRuntime: java.lang.NullPointerException: participant.attendeePin must not be null
06-24 16:36:46.888  2774  2774 E AndroidRuntime: 	at com.nextcloud.talk.controllers.ConversationInfoController.onItemClick(ConversationInfoController.kt:951)
06-24 16:36:46.888  2774  2774 E AndroidRuntime: 	at eu.davidea.viewholders.FlexibleViewHolder.onClick(FlexibleViewHolder.java:122)
06-24 16:36:46.888  2774  2774 E AndroidRuntime: 	at android.view.View.performClick(View.java:7448)
06-24 16:36:46.888  2774  2774 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:7425)
06-24 16:36:46.888  2774  2774 E AndroidRuntime: 	at android.view.View.access$3600(View.java:810)
06-24 16:36:46.888  2774  2774 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:28305)
06-24 16:36:46.888  2774  2774 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
06-24 16:36:46.888  2774  2774 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
06-24 16:36:46.888  2774  2774 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
06-24 16:36:46.888  2774  2774 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7664)
06-24 16:36:46.888  2774  2774 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-24 16:36:46.888  2774  2774 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
06-24 16:36:46.888  2774  2774 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
06-24 16:36:46.904  1122  8895 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
06-24 16:36:46.904  1122  4246 W ActivityTaskManager:   Force finishing activity com.nextcloud.talk2.qa/com.nextcloud.talk.activities.MainActivity
06-24 16:36:46.933  1122  1413 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
06-24 16:36:46.934  1122  1413 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
06-24 16:36:46.954  2774  2774 I Process : Sending signal. PID: 2774 SIG: 9
```

**Comment by AndyScherzinger** [comment]
Can you try https://github.com/nextcloud/talk-android/pull/1359#issuecomment-867692486 which should have a fix for that too :)

**Comment by AndyScherzinger** [comment]
@nickvergessen I am bullet proving the code here atm but was asking myself if `participant.attendeePin` can be null because the Android-side of the API doesn't reflect that explicitly - but if so we could make this more explicit :)

**Comment by nickvergessen** [comment]
It might be missing completely if the api version is not >= 3

**Comment by dorpauli** [comment]
@AndyScherzinger That fixed it. I can now make the group members to moderators or kick them. 😄
