### ISSUE TITLE
[Transifex] bot not pushing translations top report since 23rd June

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/talk-android#1399]
see ```$subject```

**Comment by nickvergessen** [comment]
```
 show + '[' -d src/main/res ]
+ '[' -d app/src/main/res ]
+ rm -rf app/src/main/res/values-de
+ mv app/src/main/res/values-de-rDE app/src/main/res/values-de
+ '[' -d News-Android-App/src/main/res ]
+ '[' -e scripts/metadata/generate_metadata.py ]
+ python3 scripts/metadata/generate_metadata.py

tr-TR
Parsing /app/scripts/metadata/../../app/src/main/res/values-tr/strings.xml...
Traceback (most recent call last):
  File "scripts/metadata/generate_metadata.py", line 122, in <module>
    main()
  File "scripts/metadata/generate_metadata.py", line 78, in main
    e = ElementTree.parse(strings_file).getroot()
  File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 1196, in parse
    tree.parse(source, parser)
  File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 597, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 315, column 53
```
