### ISSUE TITLE
App Crash on Android 5.1.1

### ISSUE THREAD

**Issue by blitzdose** [nextcloud/talk-android#1417]
## Steps to reproduce
1. Install the latest Version from the Google Play Store on an Android 5.1.1 EMUI 3.1 Huawei Device
2. You tap the App Icon, the Splash screen shows for about 2 seconds and then the App crashed without any error message

### Expected behaviour
The App should just start normally

### Actual behaviour
The App crashes without any error message. But Video Calls are still possible

## Device information

**Device:** Huawei M2-A01L (Tablet)

**Android version:** 5.1.1

**Talk version:** 12.1.0

## Server information

**Nextcloud version:** 21.0.3

**Talk version:** 11.2.2 (no update available)

**Custom Signaling server configured:** no

**Custom TURN server configured:** yes

**Custom STUN server configured:** no (stun.nextcloud.com:443) 

### Server log (data/nextcloud.log)
Logfile contains no entries from the day the crash happens

**Comment by mahibi** [comment]
thanks for the report @blitzdose 
this might be a problem related to huawei devices because in the playstore a review with "Crashes immediatelly after launch" was reported for a Huawei P30 Pro.

Anyone who owns a Huawei is welcomed to test and confirm!

**Comment by mahibi** [comment]
@jakobroehrl do i remember correctly you have a wide selection of devices? you have some huawei device to test that?

**Comment by AndyScherzinger** [comment]
@blitzdose if you could grab some logs, see https://github.com/nextcloud/android#getting-debug-info-via-logcat-mag on howe to do this, this might help a lot. If so you should see some lines with "talk" and "exception" these are the ones we would be looking for which point to the issue at hand.

My guess is it is:
```
com.nextcloud.talk.utils.NoSupportedApiException: 
  at com.nextcloud.talk.utils.ApiUtils.getConversationApiVersion (ApiUtils.java:146)
  at com.nextcloud.talk.controllers.ConversationsListController.fetchData (ConversationsListController.java:448)
  at com.nextcloud.talk.controllers.ConversationsListController.onAttach (ConversationsListController.java:295)
  at com.bluelinelabs.conductor.Controller.attach (Controller.java:948)
  at com.bluelinelabs.conductor.Controller$7.onAttached (Controller.java:1080)
  at com.bluelinelabs.conductor.internal.ViewAttachHandler.reportAttached (ViewAttachHandler.java:87)
  at com.bluelinelabs.conductor.internal.ViewAttachHandler$1.onAttached (ViewAttachHandler.java:47)
  at com.bluelinelabs.conductor.internal.ViewAttachHandler$2.onViewAttachedToWindow (ViewAttachHandler.java:126)
  at android.view.View.dispatchAttachedToWindow (View.java:21319)
  at android.view.ViewGroup.dispatchAttachedToWindow (ViewGroup.java:4246)
  at android.view.ViewGroup.dispatchAttachedToWindow (ViewGroup.java:4246)
  at android.view.ViewGroup.dispatchAttachedToWindow (ViewGroup.java:4246)
  at android.view.ViewGroup.dispatchAttachedToWindow (ViewGroup.java:4246)
  at android.view.ViewGroup.dispatchAttachedToWindow (ViewGroup.java:4246)
  at android.view.ViewGroup.dispatchAttachedToWindow (ViewGroup.java:4246)
  at android.view.ViewGroup.dispatchAttachedToWindow (ViewGroup.java:4246)
  at android.view.ViewGroup.dispatchAttachedToWindow (ViewGroup.java:4246)
  at android.view.ViewGroup.dispatchAttachedToWindow (ViewGroup.java:4246)
  at android.view.ViewRootImpl.performTraversals (ViewRootImpl.java:2546)
  at android.view.ViewRootImpl.doTraversal (ViewRootImpl.java:2200)
  at android.view.ViewRootImpl$TraversalRunnable.run (ViewRootImpl.java:8999)
  at android.view.Choreographer$CallbackRecord.run (Choreographer.java:996)
  at android.view.Choreographer.doCallbacks (Choreographer.java:794)
  at android.view.Choreographer.doFrame (Choreographer.java:729)
  at android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:981)
  at android.os.Handler.handleCallback (Handler.java:883)
  at android.os.Handler.dispatchMessage (Handler.java:100)
  at android.os.Looper.loop (Looper.java:237)
  at android.app.ActivityThread.main (ActivityThread.java:7860)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1068)
```

So also looping in @nickvergessen - we need to "fix" this while I can't say why we don't detect a supported API version here.

@blitzdose could you provide us a test account on your server? (via mail)

**Comment by blitzdose** [comment]
@AndyScherzinger yes I can give you a test account. To which E-Mail address should I send the credentials?

It's a bit complicated to get the logs. I know how it is done (I'm an Android developer) but the Device is the one from my parents and I live far away from them. I hope I can explain them how to do it.

**Comment by mahibi** [comment]
@blitzdose great thank you!
just send the credentials to  marcel.hibbe@nextcloud.com
i will let you know about progress and when you can delete the account again!

**Comment by mahibi** [comment]
i can reproduce the crash now with an emulator using android 5.1 ! (Pixel2 API 22)

stacktrace is:

```
07-08 11:13:33.386 3659-3659/com.nextcloud.talk2 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.nextcloud.talk2, PID: 3659
    android.content.res.Resources$NotFoundException: File res/drawable/ic_launcher_background.xml from drawable resource ID #0x7f080432
        at android.content.res.Resources.loadDrawableForCookie(Resources.java:2479)
        at android.content.res.Resources.loadDrawable(Resources.java:2381)
        at android.content.res.Resources.getDrawable(Resources.java:787)
        at android.content.Context.getDrawable(Context.java:403)
        at com.nextcloud.talk.adapters.items.ConversationItem.bindViewHolder(ConversationItem.java:219)
        at com.nextcloud.talk.adapters.items.ConversationItem.bindViewHolder(ConversationItem.java:66)
        at eu.davidea.flexibleadapter.FlexibleAdapter.onBindViewHolder(FlexibleAdapter.java:1772)
        at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
        at android.view.View.layout(View.java:15671)
        at android.view.ViewGroup.layout(ViewGroup.java:5038)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
        at android.view.View.layout(View.java:15671)
        at android.view.ViewGroup.layout(ViewGroup.java:5038)
        at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:689)
        at android.view.View.layout(View.java:15671)
        at android.view.ViewGroup.layout(ViewGroup.java:5038)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1213)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:899)
        at com.google.android.material.appbar.ViewOffsetBehavior.layoutChild(ViewOffsetBehavior.java:66)
        at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:152)
        at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:43)
        at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:2003)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:918)
        at android.view.View.layout(View.java:15671)
        at android.view.ViewGroup.layout(ViewGroup.java:5038)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
        at android.view.View.layout(View.java:15671)
        at android.view.ViewGroup.layout(ViewGroup.java:5038)
        at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:148)
        at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:43)
        at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:2003)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:918)
        at android.view.View.layout(View.java:15671)
        at android.view.ViewGroup.layout(ViewGroup.java:5038)
    	at android.widget.FrameLayout.layoutChildren(FrameLayout.ja
```

we will investigate further how to avoid this crash.
so it has nothing to do with Huawei devices but with the Android version.
thanks for your help @blitzdose ! you can now delete the test account.

**Comment by blitzdose** [comment]
Okay thank you so much for your help!

**Comment by AndyScherzinger** [comment]
@blitzdose quick workaround for you and your family: delete the "Talk Updates" conversation (its icon calculation causes the crash on old Android versions).

**Comment by AndyScherzinger** [comment]
#1420 should do the trick while I personally can't test due to HW constraints (to low-performing laptop to start an emulator)

**Comment by AndyScherzinger** [comment]
@blitzdose fixed version should show up on Google Play by tomorrow 🚀
