### ISSUE TITLE
App crashes immediately when receiving a picture

### ISSUE THREAD

**Issue by w01fg21nc** [nextcloud/talk-android#1435]
**Steps to reproduce**
   Installed the latest Version (12.1.0) from Google Play Store on an Android 7.0 Device.
   App crashes immediately when receiving a picture from chat participant.
   The App crashes without any error message. 

**Device information**
   Samsung Galaxy S7
   Android OS version: 7.0
   Talk version: 12.1.0   (v11.1.0 works well)

**Server information**
   Nextcloud version: 19.0.12
   Talk version: 9.0.10
   Custom Signaling server configured: no
   Custom TURN server configured: no
   Custom STUN server configured: no (stun.nextcloud.com:443)
   Server log (data/nextcloud.log):   Logfile contains no entries from the day the crash happens

*****
**Output of adb logcat:**

```
07-09 14:48:15.402 16419 16419 D TextView: setTypeface with style : 0
07-09 14:48:15.472 16419 16466 W System.err: at.bitfire.dav4jvm.exception.NotFoundException: HTTP 404 
07-09 14:48:15.472 16419 16466 W System.err: 	at at.bitfire.dav4jvm.DavResource.checkStatus(DavResource.kt:376)
07-09 14:48:15.472 16419 16466 W System.err: 	at at.bitfire.dav4jvm.DavResource.checkStatus(DavResource.kt:358)
07-09 14:48:15.472 16419 16466 W System.err: 	at at.bitfire.dav4jvm.DavResource.processMultiStatus(DavResource.kt:458)
07-09 14:48:15.472 16419 16466 W System.err: 	at at.bitfire.dav4jvm.DavResource.propfind(DavResource.kt:345)
07-09 14:48:15.473 16419 16466 W System.err: 	at com.nextcloud.talk.components.filebrowser.webdav.ReadFilesystemOperation.readRemotePath(ReadFilesystemOperation.java:65)
07-09 14:48:15.473 16419 16466 W System.err: 	at com.nextcloud.talk.adapters.messages.MagicPreviewMessageViewHolder$1.onSuccess(MagicPreviewMessageViewHolder.java:555)
07-09 14:48:15.473 16419 16466 W System.err: 	at com.nextcloud.talk.adapters.messages.MagicPreviewMessageViewHolder$1.onSuccess(MagicPreviewMessageViewHolder.java:547)
07-09 14:48:15.473 16419 16466 W System.err: 	at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
07-09 14:48:15.473 16419 16466 W System.err: 	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:608)
07-09 14:48:15.473 16419 16466 W System.err: 	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
07-09 14:48:15.473 16419 16466 W System.err: 	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
07-09 14:48:15.473 16419 16466 W System.err: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
07-09 14:48:15.473 16419 16466 W System.err: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
07-09 14:48:15.473 16419 16466 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
07-09 14:48:15.473 16419 16466 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
07-09 14:48:15.473 16419 16466 W System.err: 	at java.lang.Thread.run(Thread.java:762)
07-09 14:48:15.474 16419 16466 W System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'okhttp3.HttpUrl at.bitfire.dav4jvm.Response.getHref()' on a null object reference
07-09 14:48:15.475 16419 16466 W System.err: 	at com.nextcloud.talk.components.filebrowser.webdav.ReadFilesystemOperation.readRemotePath(ReadFilesystemOperation.java:91)
07-09 14:48:15.475 16419 16466 W System.err: 	at com.nextcloud.talk.adapters.messages.MagicPreviewMessageViewHolder$1.onSuccess(MagicPreviewMessageViewHolder.java:555)
07-09 14:48:15.475 16419 16466 W System.err: 	at com.nextcloud.talk.adapters.messages.MagicPreviewMessageViewHolder$1.onSuccess(MagicPreviewMessageViewHolder.java:547)
07-09 14:48:15.475 16419 16466 W System.err: 	at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
07-09 14:48:15.475 16419 16466 W System.err: 	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:608)
07-09 14:48:15.475 16419 16466 W System.err: 	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
07-09 14:48:15.475 16419 16466 W System.err: 	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
07-09 14:48:15.475 16419 16466 W System.err: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
07-09 14:48:15.475 16419 16466 W System.err: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
07-09 14:48:15.475 16419 16466 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
07-09 14:48:15.475 16419 16466 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
07-09 14:48:15.475 16419 16466 W System.err: 	at java.lang.Thread.run(Thread.java:762)
07-09 14:48:15.484 16419 16466 E AndroidRuntime: FATAL EXCEPTION: RxCachedThreadScheduler-4
07-09 14:48:15.484 16419 16466 E AndroidRuntime: Process: com.nextcloud.talk2, PID: 16419
07-09 14:48:15.484 16419 16466 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'okhttp3.HttpUrl at.bitfire.dav4jvm.Response.getHref()' on a null object reference
07-09 14:48:15.484 16419 16466 E AndroidRuntime: 	at com.nextcloud.talk.components.filebrowser.webdav.ReadFilesystemOperation.readRemotePath(ReadFilesystemOperation.java:91)
07-09 14:48:15.484 16419 16466 E AndroidRuntime: 	at com.nextcloud.talk.adapters.messages.MagicPreviewMessageViewHolder$1.onSuccess(MagicPreviewMessageViewHolder.java:555)
07-09 14:48:15.484 16419 16466 E AndroidRuntime: 	at com.nextcloud.talk.adapters.messages.MagicPreviewMessageViewHolder$1.onSuccess(MagicPreviewMessageViewHolder.java:547)
07-09 14:48:15.484 16419 16466 E AndroidRuntime: 	at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
07-09 14:48:15.484 16419 16466 E AndroidRuntime: 	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:608)
07-09 14:48:15.484 16419 16466 E AndroidRuntime: 	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
07-09 14:48:15.484 16419 16466 E AndroidRuntime: 	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
07-09 14:48:15.484 16419 16466 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
07-09 14:48:15.484 16419 16466 E AndroidRuntime: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
07-09 14:48:15.484 16419 16466 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
07-09 14:48:15.484 16419 16466 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
07-09 14:48:15.484 16419 16466 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:762)
07-09 14:48:15.498  3858  3879 D InputDispatcher: Focus left window: 16419
07-09 14:48:15.499 16419 16419 D ViewRootImpl@cd44916[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 0
07-09 14:48:16.056 16419 16419 D InputMethodManager: HSI from window - flag : 0 Pid : 16419
07-09 14:48:16.074 16419 16419 D ViewRootImpl@cd44916[MainActivity]: dispatchDetachedFromWindow
07-09 14:48:16.087 16419 16419 D InputTransport: Input channel destroyed: fd=83
```

*****
Then installed the Talk QA 1420.apk from #1420, same error occured.
**adb logcat for 1420.apk:**

```
07-09 14:52:48.891 16871 16902 W System.err: at.bitfire.dav4jvm.exception.NotFoundException: HTTP 404 
07-09 14:52:48.892 16871 16902 W System.err: 	at at.bitfire.dav4jvm.DavResource.checkStatus(DavResource.kt:376)
07-09 14:52:48.892 16871 16902 W System.err: 	at at.bitfire.dav4jvm.DavResource.checkStatus(DavResource.kt:358)
07-09 14:52:48.892 16871 16902 W System.err: 	at at.bitfire.dav4jvm.DavResource.processMultiStatus(DavResource.kt:458)
07-09 14:52:48.892 16871 16902 W System.err: 	at at.bitfire.dav4jvm.DavResource.propfind(DavResource.kt:345)
07-09 14:52:48.892 16871 16902 W System.err: 	at com.nextcloud.talk.components.filebrowser.webdav.ReadFilesystemOperation.readRemotePath(ReadFilesystemOperation.java:65)
07-09 14:52:48.892 16871 16902 W System.err: 	at com.nextcloud.talk.adapters.messages.MagicPreviewMessageViewHolder$1.onSuccess(MagicPreviewMessageViewHolder.java:555)
07-09 14:52:48.892 16871 16902 W System.err: 	at com.nextcloud.talk.adapters.messages.MagicPreviewMessageViewHolder$1.onSuccess(MagicPreviewMessageViewHolder.java:547)
07-09 14:52:48.892 16871 16902 W System.err: 	at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
07-09 14:52:48.892 16871 16902 W System.err: 	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:608)
07-09 14:52:48.892 16871 16902 W System.err: 	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
07-09 14:52:48.892 16871 16902 W System.err: 	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
07-09 14:52:48.892 16871 16902 W System.err: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
07-09 14:52:48.892 16871 16902 W System.err: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
07-09 14:52:48.893 16871 16902 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
07-09 14:52:48.893 16871 16902 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
07-09 14:52:48.893 16871 16902 W System.err: 	at java.lang.Thread.run(Thread.java:762)
07-09 14:52:48.894 16871 16902 W System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'okhttp3.HttpUrl at.bitfire.dav4jvm.Response.getHref()' on a null object reference
07-09 14:52:48.894 16871 16902 W System.err: 	at com.nextcloud.talk.components.filebrowser.webdav.ReadFilesystemOperation.readRemotePath(ReadFilesystemOperation.java:91)
07-09 14:52:48.894 16871 16902 W System.err: 	at com.nextcloud.talk.adapters.messages.MagicPreviewMessageViewHolder$1.onSuccess(MagicPreviewMessageViewHolder.java:555)
07-09 14:52:48.894 16871 16902 W System.err: 	at com.nextcloud.talk.adapters.messages.MagicPreviewMessageViewHolder$1.onSuccess(MagicPreviewMessageViewHolder.java:547)
07-09 14:52:48.894 16871 16902 W System.err: 	at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
07-09 14:52:48.894 16871 16902 W System.err: 	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:608)
07-09 14:52:48.894 16871 16902 W System.err: 	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
07-09 14:52:48.895 16871 16902 W System.err: 	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
07-09 14:52:48.895 16871 16902 W System.err: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
07-09 14:52:48.895 16871 16902 W System.err: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
07-09 14:52:48.895 16871 16902 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
07-09 14:52:48.895 16871 16902 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
07-09 14:52:48.895 16871 16902 W System.err: 	at java.lang.Thread.run(Thread.java:762)
07-09 14:52:48.905 16871 16902 E AndroidRuntime: FATAL EXCEPTION: RxCachedThreadScheduler-1
07-09 14:52:48.905 16871 16902 E AndroidRuntime: Process: com.nextcloud.talk2.qa, PID: 16871
07-09 14:52:48.905 16871 16902 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'okhttp3.HttpUrl at.bitfire.dav4jvm.Response.getHref()' on a null object reference
07-09 14:52:48.905 16871 16902 E AndroidRuntime: 	at com.nextcloud.talk.components.filebrowser.webdav.ReadFilesystemOperation.readRemotePath(ReadFilesystemOperation.java:91)
07-09 14:52:48.905 16871 16902 E AndroidRuntime: 	at com.nextcloud.talk.adapters.messages.MagicPreviewMessageViewHolder$1.onSuccess(MagicPreviewMessageViewHolder.java:555)
07-09 14:52:48.905 16871 16902 E AndroidRuntime: 	at com.nextcloud.talk.adapters.messages.MagicPreviewMessageViewHolder$1.onSuccess(MagicPreviewMessageViewHolder.java:547)
07-09 14:52:48.905 16871 16902 E AndroidRuntime: 	at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
07-09 14:52:48.905 16871 16902 E AndroidRuntime: 	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:608)
07-09 14:52:48.905 16871 16902 E AndroidRuntime: 	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
07-09 14:52:48.905 16871 16902 E AndroidRuntime: 	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
07-09 14:52:48.905 16871 16902 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
07-09 14:52:48.905 16871 16902 E AndroidRuntime: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
07-09 14:52:48.905 16871 16902 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
07-09 14:52:48.905 16871 16902 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
07-09 14:52:48.905 16871 16902 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:762)
07-09 14:52:48.916  3858  5207 D InputDispatcher: Focus left window: 16871
07-09 14:52:48.917 16871 16871 D ViewRootImpl@8d8cbc8[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 0
```

*****
Talk app 12.1.0 works well on my 2nd phone with Android 10.

Thanks for help.

**Comment by w01fg21nc** [comment]
**Update:**

App also crashes when sending/receiving pdf files, text only works well.

*****
**adb logcat:**

07-11 09:56:46.678 21782 21823 E AndroidRuntime: FATAL EXCEPTION: RxCachedThreadScheduler-3
07-11 09:56:46.678 21782 21823 E AndroidRuntime: Process: com.nextcloud.talk2, PID: 21782
07-11 09:56:46.678 21782 21823 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'okhttp3.HttpUrl at.bitfire.dav4jvm.Response.getHref()' on a null object reference
07-11 09:56:46.678 21782 21823 E AndroidRuntime: 	at com.nextcloud.talk.components.filebrowser.webdav.ReadFilesystemOperation.readRemotePath(ReadFilesystemOperation.java:91)
07-11 09:56:46.678 21782 21823 E AndroidRuntime: 	at com.nextcloud.talk.adapters.messages.MagicPreviewMessageViewHolder$1.onSuccess(MagicPreviewMessageViewHolder.java:555)
07-11 09:56:46.678 21782 21823 E AndroidRuntime: 	at com.nextcloud.talk.adapters.messages.MagicPreviewMessageViewHolder$1.onSuccess(MagicPreviewMessageViewHolder.java:547)
07-11 09:56:46.678 21782 21823 E AndroidRuntime: 	at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
07-11 09:56:46.678 21782 21823 E AndroidRuntime: 	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:608)
07-11 09:56:46.678 21782 21823 E AndroidRuntime: 	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
07-11 09:56:46.678 21782 21823 E AndroidRuntime: 	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
07-11 09:56:46.678 21782 21823 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
07-11 09:56:46.678 21782 21823 E AndroidRuntime: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
07-11 09:56:46.678 21782 21823 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
07-11 09:56:46.678 21782 21823 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
07-11 09:56:46.678 21782 21823 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:762)
07-11 09:56:46.690  3858  4058 D InputDispatcher: Focus left window: 21782
07-11 09:56:46.691 21782 21782 D ViewRootImpl@9c79bbc[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 0
07-11 09:56:47.229 21782 21782 D InputMethodManager: HSI from window - flag : 0 Pid : 21782
07-11 09:56:47.247 21782 21782 D ViewRootImpl@9c79bbc[MainActivity]: dispatchDetachedFromWindow
07-11 09:56:47.258 21782 21782 D InputTransport: Input channel destroyed: fd=83

**Comment by AndyScherzinger** [comment]
hmmm, you ssem to receive http 404 responses. Any ideas @nickvergessen / @mahibi. Other than that we probably shouldn't crash but rath fallback to showing an error-images.

**Comment by w01fg21nc** [comment]
Some additional info:
First phone with Android 7:  It seems like every kind of a shared file (send/receive, tested with .jpg and .pdf so far) crashes the Talk app v 12.1.0 (also 12.1.1). Only text messages and html-links work well.  Talk app v11.1.0 and lower worked fine.

On my second phone with Android 10 there are no problems with Talk v12.1.1 

No changes were made on my self-hosted Nextcloud server in the last couple of weeks.

Other user of my NC with Talk v12.1.0 does not report any problems.

**Comment by AndyScherzinger** [comment]
text/links aren't files, so it seems loading/accessing file sis an issue which leads to 404s on your device. 

* Is it the same account on several devices on is the issue linked to a specific account?
* Is anything else different (app updated, new install, re-install). Trying to find the difference.
* Could you try to re-authorize (via the settings)?
* Did you already try to re-install? (just asking)

**Comment by w01fg21nc** [comment]
- I use the same account on both phones. Issue is linked to my older phone with Android 7 only and Talk app v12.1.0 and 12.1.1.
- Until the beginning of last week I used v11.1.0 on my older phone. Was not installed on the second phone. Around Wednesday I checked Google Play store for updates and installed v12.1.0. When the first issue happened I installed Talk 12.1.0 on my second phone.
- re-authorize did not fix the problem
- Reinstallations (several times since Friday) did not fix the problem

**Comment by AndyScherzinger** [comment]
I hope  @nickvergessen / @mahibi might have an idea about a possible cause

**Comment by mahibi** [comment]
i guess somehow the mimetype of the files is not found and then 
com.nextcloud.talk.adapters.messages.MagicPreviewMessageViewHolder#fetchFileInformation
is executed which then fails to read the url in 
com.nextcloud.talk.components.filebrowser.webdav.ReadFilesystemOperation#readRemotePath

But honestly i don't even know what "fetchFileInformation" is still useful for.
Apparently this was kept as a fallback if the other conditions don't match. Obviously it's still called now (on purpose or because of a mistake..)

**Comment by mahibi** [comment]
@w01fg21nc i assume you tried exactly the same files in the same chat but with different android devices right?

**Comment by w01fg21nc** [comment]
Yes, that's right, but the file type doesn't matter. Tried with .jpg, .png, .pdf, .docx and .ods.
Send/receive any kind of a shared file via PC browser or Talk app on my Android 10 device works well. But when I use my Android 7 device to view the file again (or to send another file) the Talk app crashes. There is no parallel use of my devices.

**Comment by mahibi** [comment]
according to google play console this crash affects 35 users (56 total occurences).
i had a closer look yesterday (see https://github.com/nextcloud/talk-android/issues/1510#issuecomment-909531062) but i have no idea so far...

**Comment by w01fg21nc** [comment]
Thanks @mahibi for your deeper analysis. In the meantime I upgraded Nextcloud server to 21.0.4 but nothing changed regarding my problem. So far I will stay at Talk 11.1 on my older device with no problems. Later this year I plan to upgrade my older device to a newer OS version like Lineage 16 or something similar. Then I will try again Talk 12.x

**Comment by iprok** [comment]
Hello! I've also faced the issue with nextcloud 21.0.7 and Nextcloud Talk 13.0.0 for android. The same logs on the phone side, buy I also got the request that leads to 404 error from the server logs:
/thecloud/index.php/core/preview?fileId=iprok&x=605&y=605&a=1&mode=cover&forceIcon=1

I've also grepped the logs for other requests to /core/preview and the request from Talk doesn't look valid. Correct value of fileid should be digit.

I also simulated the request using curl (with all needed authorization headers). Here is the answer:
```
< HTTP/2 404 
< server: nginx
< date: Thu, 02 Dec 2021 06:58:25 GMT
< content-type: application/json; charset=utf-8
< content-length: 2
< expires: Thu, 19 Nov 1981 08:52:00 GMT
< pragma: no-cache
< cache-control: no-cache, no-store, must-revalidate
< content-security-policy: default-src 'none';base-uri 'none';manifest-src 'self';frame-ancestors 'none'
< feature-policy: autoplay 'none';camera 'none';fullscreen 'none';geolocation 'none';microphone 'none';payment 'none'
< x-robots-tag: none
< referrer-policy: no-referrer
< x-content-type-options: nosniff
< x-download-options: noopen
< x-frame-options: SAMEORIGIN
< x-permitted-cross-domain-policies: none
< x-robots-tag: none
< x-xss-protection: 1; mode=block
< strict-transport-security: max-age=15768000; includeSubDomains; preload;
< 
* Connection #0 to host cloud.kinetiksoft.com left intact
[]
```

Hope that this can help you to resolve the issue

**Comment by w01fg21nc** [comment]
Hello @mahibi, it's been a long time, but I've found a working image (LOS19) for my old device in January. Since that time I use Talk App version 13.0 with no problems, so my issue can be closed.
