### ISSUE TITLE
NPE in ConversationsListController.checkToShowUnreadBubble

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/talk-android#1596]
## Steps to reproduce
1. open the app and click after a short time to open a conversation from the list, maybe try back&forth for a while
2. hit an NPE
3.

### Expected behaviour
No NPE

### Actual behaviour
NPE

java.lang.NullPointerException: Attempt to invoke virtual method 'void com.webianks.library.PopupBubble.hide()' on a null object reference
        at com.nextcloud.talk.controllers.ConversationsListController.checkToShowUnreadBubble(ConversationsListController.java:640)
        at com.nextcloud.talk.controllers.ConversationsListController.lambda$ra_tPWElN3DSYgNYdA7_Hib6xo0(Unknown Source:0)
        at com.nextcloud.talk.controllers.-$$Lambda$ConversationsListController$ra_tPWElN3DSYgNYdA7_Hib6xo0.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:233)
        at android.app.ActivityThread.main(ActivityThread.java:8035)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)

## Device information

**Device:** OP9Pro

**Android version:** 11

**Talk version:** master

## Server information

**Nextcloud version:** c.nc.c

**Talk version:** latest

**Comment by AndyScherzinger** [comment]
@mahibi this must have come in with the latest PR regarding the unread bubble and is likely caused by:

```
new Handler().postDelayed(this::checkToShowUnreadBubble, UNREAD_BUBBLE_DELAY);
```
which is the lambda referenced at the top which will be asynchronous and in case I open a conversation and this get triggered afterwards, the UI will be destroyed already and the bound UI element is null, so this needs to be made null-safe or you need to try/catch it since is is asynchronous so even after the check the object might get killed before you actually call it...
