### ISSUE TITLE
"Big" video files are making the app crash

### ISSUE THREAD

**Issue by RphCos** [nextcloud/talk-android#1603]
## Steps to reproduce
1. Either have a video file around 700M on your nextcloud or on the mobile device (Android) .
2. Either share the nextcloud file or upload the video from local device
3. If you shared the nextcloud file, then click on it to try to view it.

### Expected behaviour
The video should be downloaded then played, or the App should warn us that such big file cannot be uploaded.

### Actual behaviour
1 - The App crashes when you try to view the video that was uploaded on Nextcloud.
2 - The App crashes if you try to upload the video from the local device

In some case, when trying with 300-500M mp4 files uploaded on nextcloud, the App crashes but then the download starts after booting the app back, allowing us to see the video normaly. On some other occurence it will just create a loop of crashes until Android detects the app is only crashing and stops it.

Smaller video files (around 200M), download and play flawlessly.

**There are absolutely no problem viewing downloading or uploading the same videos from a Desktop Browser.**

## Device information

**DeviceS:**
 OnePlus 6
 OnePlus 6T
 Redmi Note 9 Pro
 
 All devices runing on Android 10.
 
 **Android Talk App Version**: 12.2.1 (on all devices)

## Server information

**Nextcloud version:** 22.1.1

**Talk version:** 12.1.2

**Custom Signaling server configured:** no 

**Custom TURN server configured:** no 

**Custom STUN server configured:** no 

### Server log (data/nextcloud.log)

No logs when triggering the crashes.

**Comment by mahibi** [comment]
just reproduced this. Error:

```
2021-10-04 18:39:04.411 2284-2551/com.nextcloud.talk2 I/WM-WorkerWrapper: Worker result SUCCESS for Work [ id=46f25d13-192d-48a8-a1ee-76c0f8d97bd9, tags={ com.nextcloud.talk.jobs.UploadAndShareFilesWorker } ]
2021-10-04 18:39:04.444 2284-2653/com.nextcloud.talk2 I/okhttp.OkHttpClient: --> PUT http://......../.........../remote.php/dav/files/user1/Talk/.............mp4
2021-10-04 18:39:04.445 2284-2653/com.nextcloud.talk2 I/okhttp.OkHttpClient: Content-Type: application/octet-stream
2021-10-04 18:39:04.445 2284-2653/com.nextcloud.talk2 I/okhttp.OkHttpClient: Content-Length: 381751880
2021-10-04 18:39:04.446 2284-2653/com.nextcloud.talk2 I/okhttp.OkHttpClient: Authorization: ██
2021-10-04 18:39:04.447 2284-2653/com.nextcloud.talk2 I/okhttp.OkHttpClient: User-Agent: Mozilla/5.0 (Android) Nextcloud-Talk v12.3.0 Alpha 09
2021-10-04 18:39:04.447 2284-2653/com.nextcloud.talk2 I/okhttp.OkHttpClient: Accept: application/json
2021-10-04 18:39:04.448 2284-2653/com.nextcloud.talk2 I/okhttp.OkHttpClient: OCS-APIRequest: true
2021-10-04 18:39:04.734 2284-2300/com.nextcloud.talk2 W/System: A resource failed to call close. 
2021-10-04 18:39:05.599 2284-2302/com.nextcloud.talk2 I/nextcloud.talk: Clamp target GC heap from 515MB to 512MB
2021-10-04 18:39:05.602 2840-5823/? I/DPMJ: |REQ:RCVR| DPM creating socket
2021-10-04 18:39:05.799 2284-2653/com.nextcloud.talk2 I/nextcloud.talk: Waiting for a blocking GC Alloc
2021-10-04 18:39:05.879 2284-2302/com.nextcloud.talk2 I/nextcloud.talk: Clamp target GC heap from 535MB to 512MB
2021-10-04 18:39:05.879 2284-2653/com.nextcloud.talk2 I/nextcloud.talk: WaitForGcToComplete blocked Alloc on HeapTrim for 80.213ms
2021-10-04 18:39:05.879 2284-2653/com.nextcloud.talk2 I/nextcloud.talk: Starting a blocking GC Alloc
2021-10-04 18:39:05.894 2284-2653/com.nextcloud.talk2 I/nextcloud.talk: Waiting for a blocking GC Alloc
2021-10-04 18:39:05.939 2284-2302/com.nextcloud.talk2 I/nextcloud.talk: Clamp target GC heap from 535MB to 512MB
2021-10-04 18:39:05.939 2284-2653/com.nextcloud.talk2 I/nextcloud.talk: WaitForGcToComplete blocked Alloc on HeapTrim for 44.603ms
2021-10-04 18:39:05.939 2284-2653/com.nextcloud.talk2 I/nextcloud.talk: Starting a blocking GC Alloc
2021-10-04 18:39:05.940 2284-2653/com.nextcloud.talk2 I/nextcloud.talk: Waiting for a blocking GC Alloc
2021-10-04 18:39:05.947 2284-2284/com.nextcloud.talk2 I/nextcloud.talk: Waiting for a blocking GC Alloc
2021-10-04 18:39:05.991 2284-2302/com.nextcloud.talk2 I/nextcloud.talk: Clamp target GC heap from 535MB to 512MB
2021-10-04 18:39:05.992 2284-2653/com.nextcloud.talk2 I/nextcloud.talk: WaitForGcToComplete blocked Alloc on HeapTrim for 51.836ms
2021-10-04 18:39:05.992 2284-2653/com.nextcloud.talk2 I/nextcloud.talk: Starting a blocking GC Alloc
2021-10-04 18:39:05.992 2284-2653/com.nextcloud.talk2 I/nextcloud.talk: Waiting for a blocking GC Alloc
2021-10-04 18:39:05.992 2284-2284/com.nextcloud.talk2 I/nextcloud.talk: Waiting for a blocking GC Alloc
2021-10-04 18:39:06.044 2284-2302/com.nextcloud.talk2 I/nextcloud.talk: Clamp target GC heap from 535MB to 512MB
2021-10-04 18:39:06.044 2284-2653/com.nextcloud.talk2 I/nextcloud.talk: WaitForGcToComplete blocked Alloc on HeapTrim for 52.312ms
2021-10-04 18:39:06.044 2284-2653/com.nextcloud.talk2 I/nextcloud.talk: Starting a blocking GC Alloc
2021-10-04 18:39:06.045 2284-2653/com.nextcloud.talk2 I/nextcloud.talk: Starting a blocking GC Alloc
2021-10-04 18:39:06.046 2284-2284/com.nextcloud.talk2 I/nextcloud.talk: Waiting for a blocking GC Alloc
2021-10-04 18:39:06.211 2284-2653/com.nextcloud.talk2 I/nextcloud.talk: Clamp target GC heap from 535MB to 512MB
2021-10-04 18:39:06.211 2284-2653/com.nextcloud.talk2 I/nextcloud.talk: Alloc concurrent copying GC freed 35(784B) AllocSpace objects, 0(0B) LOS objects, 0% free, 511MB/512MB, paused 214us total 165.902ms
2021-10-04 18:39:06.211 2284-2284/com.nextcloud.talk2 I/nextcloud.talk: WaitForGcToComplete blocked Alloc on HeapTrim for 264.166ms
2021-10-04 18:39:06.211 2284-2284/com.nextcloud.talk2 I/nextcloud.talk: Starting a blocking GC Alloc
2021-10-04 18:39:06.212 2284-2653/com.nextcloud.talk2 I/nextcloud.talk: Starting a blocking GC Alloc
2021-10-04 18:39:06.307 2284-2653/com.nextcloud.talk2 I/nextcloud.talk: Clamp target GC heap from 535MB to 512MB
2021-10-04 18:39:06.307 2284-2653/com.nextcloud.talk2 I/nextcloud.talk: Alloc concurrent copying GC freed 7(176B) AllocSpace objects, 0(0B) LOS objects, 0% free, 511MB/512MB, paused 319us total 95.321ms
2021-10-04 18:39:06.307 2284-2653/com.nextcloud.talk2 I/nextcloud.talk: Forcing collection of SoftReferences for 8KB allocation
2021-10-04 18:39:06.307 2284-2653/com.nextcloud.talk2 I/nextcloud.talk: Starting a blocking GC Alloc
2021-10-04 18:39:06.335 2309-2324/? W/NotificationService: Toast already killed. pkg=com.nextcloud.talk2 callback=android.app.ITransientNotification$Stub$Proxy@3574253
2021-10-04 18:39:06.487 2284-2284/com.nextcloud.talk2 I/nextcloud.talk: Waiting for a blocking GC Alloc
2021-10-04 18:39:06.617 2284-2653/com.nextcloud.talk2 I/nextcloud.talk: Clamp target GC heap from 535MB to 512MB
2021-10-04 18:39:06.617 2284-2653/com.nextcloud.talk2 I/nextcloud.talk: Alloc concurrent copying GC freed 5650(272KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 511MB/512MB, paused 228us total 309.540ms
2021-10-04 18:39:06.618 2284-2302/com.nextcloud.talk2 I/nextcloud.talk: WaitForGcToComplete blocked Background on HeapTrim for 405.842ms
2021-10-04 18:39:06.619 2284-2284/com.nextcloud.talk2 I/nextcloud.talk: WaitForGcToComplete blocked Alloc on HeapTrim for 131.713ms
2021-10-04 18:39:06.619 2284-2284/com.nextcloud.talk2 I/nextcloud.talk: Starting a blocking GC Alloc
2021-10-04 18:39:06.620 2284-2653/com.nextcloud.talk2 I/nextcloud.talk: Starting a blocking GC Alloc
2021-10-04 18:39:06.620 2284-2653/com.nextcloud.talk2 I/nextcloud.talk: Starting a blocking GC Alloc
2021-10-04 18:39:06.633 2284-2284/com.nextcloud.talk2 I/nextcloud.talk: Waiting for a blocking GC Alloc
2021-10-04 18:39:06.672 2284-2653/com.nextcloud.talk2 I/nextcloud.talk: Clamp target GC heap from 535MB to 512MB
2021-10-04 18:39:06.672 2284-2653/com.nextcloud.talk2 I/nextcloud.talk: Alloc concurrent copying GC freed 157(9KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 511MB/512MB, paused 131us total 52.200ms
2021-10-04 18:39:06.673 2284-2302/com.nextcloud.talk2 I/nextcloud.talk: WaitForGcToComplete blocked Background on HeapTrim for 52.341ms
2021-10-04 18:39:06.673 2284-2284/com.nextcloud.talk2 I/nextcloud.talk: WaitForGcToComplete blocked Alloc on HeapTrim for 40.057ms
2021-10-04 18:39:06.673 2284-2284/com.nextcloud.talk2 I/nextcloud.talk: Starting a blocking GC Alloc
2021-10-04 18:39:06.673 2284-2653/com.nextcloud.talk2 I/nextcloud.talk: Starting a blocking GC Alloc
2021-10-04 18:39:06.673 2284-2653/com.nextcloud.talk2 I/nextcloud.talk: Starting a blocking GC Alloc
2021-10-04 18:39:06.725 2284-2653/com.nextcloud.talk2 I/nextcloud.talk: Clamp target GC heap from 535MB to 512MB
2021-10-04 18:39:06.725 2284-2653/com.nextcloud.talk2 I/nextcloud.talk: Alloc concurrent copying GC freed 30(672B) AllocSpace objects, 0(0B) LOS objects, 0% free, 511MB/512MB, paused 118us total 52.018ms
2021-10-04 18:39:06.725 2284-2653/com.nextcloud.talk2 I/nextcloud.talk: Starting a blocking GC Alloc
2021-10-04 18:39:06.735 2284-2284/com.nextcloud.talk2 I/nextcloud.talk: Waiting for a blocking GC Alloc
2021-10-04 18:39:06.776 2284-2653/com.nextcloud.talk2 I/nextcloud.talk: Clamp target GC heap from 535MB to 512MB
2021-10-04 18:39:06.776 2284-2653/com.nextcloud.talk2 I/nextcloud.talk: Alloc concurrent copying GC freed 58(1208B) AllocSpace objects, 0(0B) LOS objects, 0% free, 511MB/512MB, paused 108us total 50.959ms
2021-10-04 18:39:06.776 2284-2653/com.nextcloud.talk2 I/nextcloud.talk: Forcing collection of SoftReferences for 8KB allocation
2021-10-04 18:39:06.776 2284-2653/com.nextcloud.talk2 I/nextcloud.talk: Starting a blocking GC Alloc
2021-10-04 18:39:06.776 2284-2284/com.nextcloud.talk2 I/nextcloud.talk: Waiting for a blocking GC Alloc
2021-10-04 18:39:06.957 2284-2653/com.nextcloud.talk2 I/nextcloud.talk: Clamp target GC heap from 535MB to 512MB
2021-10-04 18:39:06.957 2284-2653/com.nextcloud.talk2 I/nextcloud.talk: Alloc concurrent copying GC freed 317(14KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 511MB/512MB, paused 75us total 180.655ms
2021-10-04 18:39:06.957 2284-2302/com.nextcloud.talk2 I/nextcloud.talk: WaitForGcToComplete blocked Background on HeapTrim for 284.246ms
2021-10-04 18:39:06.957 2284-2284/com.nextcloud.talk2 I/nextcloud.talk: WaitForGcToComplete blocked Alloc on HeapTrim for 222.377ms
2021-10-04 18:39:06.957 2284-2284/com.nextcloud.talk2 I/nextcloud.talk: Starting a blocking GC Alloc
2021-10-04 18:39:06.957 2284-2653/com.nextcloud.talk2 I/nextcloud.talk: Starting a blocking GC Alloc
2021-10-04 18:39:06.957 2284-2653/com.nextcloud.talk2 I/nextcloud.talk: Starting a blocking GC Alloc
2021-10-04 18:39:07.010 2284-2653/com.nextcloud.talk2 I/nextcloud.talk: Clamp target GC heap from 535MB to 512MB
2021-10-04 18:39:07.010 2284-2653/com.nextcloud.talk2 I/nextcloud.talk: Alloc concurrent copying GC freed 1(56B) AllocSpace objects, 0(0B) LOS objects, 0% free, 511MB/512MB, paused 114us total 52.846ms
2021-10-04 18:39:07.010 2284-2653/com.nextcloud.talk2 I/nextcloud.talk: Starting a blocking GC Alloc
2021-10-04 18:39:07.062 2284-2653/com.nextcloud.talk2 I/nextcloud.talk: Clamp target GC heap from 535MB to 512MB
2021-10-04 18:39:07.062 2284-2653/com.nextcloud.talk2 I/nextcloud.talk: Alloc concurrent copying GC freed 67(1352B) AllocSpace objects, 0(0B) LOS objects, 0% free, 511MB/512MB, paused 76us total 51.343ms
2021-10-04 18:39:07.062 2284-2653/com.nextcloud.talk2 I/nextcloud.talk: Forcing collection of SoftReferences for 8KB allocation
2021-10-04 18:39:07.062 2284-2653/com.nextcloud.talk2 I/nextcloud.talk: Starting a blocking GC Alloc
2021-10-04 18:39:07.226 2284-2284/com.nextcloud.talk2 I/nextcloud.talk: Waiting for a blocking GC Alloc
2021-10-04 18:39:07.246 2284-2653/com.nextcloud.talk2 I/nextcloud.talk: Clamp target GC heap from 535MB to 512MB
2021-10-04 18:39:07.246 2284-2653/com.nextcloud.talk2 I/nextcloud.talk: Alloc concurrent copying GC freed 100(3KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 511MB/512MB, paused 85us total 183.871ms
2021-10-04 18:39:07.246 2284-2302/com.nextcloud.talk2 I/nextcloud.talk: WaitForGcToComplete blocked Background on HeapTrim for 288.727ms
2021-10-04 18:39:07.247 2284-2284/com.nextcloud.talk2 I/nextcloud.talk: Waiting for a blocking GC Alloc
2021-10-04 18:39:07.291 2284-2653/com.nextcloud.talk2 W/nextcloud.talk: Throwing OutOfMemoryError "Failed to allocate a 8208 byte allocation with 3224 free bytes and 3KB until OOM, max allowed footprint 536870912, growth limit 536870912"
2021-10-04 18:39:07.297 2284-2653/com.nextcloud.talk2 I/nextcloud.talk: Waiting for a blocking GC Alloc
2021-10-04 18:39:07.372 2284-2302/com.nextcloud.talk2 I/nextcloud.talk: Background concurrent copying GC freed 35625(139MB) AllocSpace objects, 0(0B) LOS objects, 6% free, 372MB/396MB, paused 2.371ms total 125.585ms
2021-10-04 18:39:07.373 2284-2284/com.nextcloud.talk2 I/nextcloud.talk: WaitForGcToComplete blocked Alloc on HeapTrim for 146.384ms
2021-10-04 18:39:07.373 2284-2284/com.nextcloud.talk2 I/nextcloud.talk: Starting a blocking GC Alloc
2021-10-04 18:39:07.373 2284-2653/com.nextcloud.talk2 I/nextcloud.talk: WaitForGcToComplete blocked Alloc on HeapTrim for 76.152ms
2021-10-04 18:39:07.373 2284-2653/com.nextcloud.talk2 I/nextcloud.talk: Starting a blocking GC Alloc
2021-10-04 18:39:07.388 2284-2653/com.nextcloud.talk2 W/System.err: io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.lang.OutOfMemoryError: Failed to allocate a 8208 byte allocation with 3224 free bytes and 3KB until OOM, max allowed footprint 536870912, growth limit 536870912
2021-10-04 18:39:07.404 2284-2653/com.nextcloud.talk2 W/System.err:     at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
2021-10-04 18:39:07.405 2284-2653/com.nextcloud.talk2 W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:69)
2021-10-04 18:39:07.406 2284-2653/com.nextcloud.talk2 W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
2021-10-04 18:39:07.406 2284-2653/com.nextcloud.talk2 W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2021-10-04 18:39:07.407 2284-2653/com.nextcloud.talk2 W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
2021-10-04 18:39:07.408 2284-2653/com.nextcloud.talk2 W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2021-10-04 18:39:07.408 2284-2653/com.nextcloud.talk2 W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2021-10-04 18:39:07.409 2284-2653/com.nextcloud.talk2 W/System.err:     at java.lang.Thread.run(Thread.java:764)
2021-10-04 18:39:07.420 2284-2653/com.nextcloud.talk2 W/System.err: Caused by: java.lang.OutOfMemoryError: Failed to allocate a 8208 byte allocation with 3224 free bytes and 3KB until OOM, max allowed footprint 536870912, growth limit 536870912
2021-10-04 18:39:07.423 2284-2653/com.nextcloud.talk2 W/System.err:     at okio.Segment.<init>(Segment.kt:62)
2021-10-04 18:39:07.426 2284-2653/com.nextcloud.talk2 W/System.err:     at okio.SegmentPool.take(SegmentPool.kt:88)
2021-10-04 18:39:07.428 2284-2653/com.nextcloud.talk2 W/System.err:     at okio.Buffer.writableSegment$okio(Buffer.kt:1423)
2021-10-04 18:39:07.430 2284-2653/com.nextcloud.talk2 W/System.err:     at okio.Buffer.write(Buffer.kt:1242)
2021-10-04 18:39:07.434 2284-2653/com.nextcloud.talk2 W/System.err:     at okio.Buffer.write(Buffer.kt:76)
2021-10-04 18:39:07.438 2284-2653/com.nextcloud.talk2 W/System.err:     at okhttp3.RequestBody$Companion$toRequestBody$2.writeTo(RequestBody.kt:152)
2021-10-04 18:39:07.442 2284-2653/com.nextcloud.talk2 W/System.err:     at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:202)
2021-10-04 18:39:07.445 2284-2653/com.nextcloud.talk2 W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2021-10-04 18:39:07.450 2284-2653/com.nextcloud.talk2 W/System.err:     at com.nextcloud.talk.dagger.modules.RestModule$HeadersInterceptor.intercept(RestModule.java:254)
2021-10-04 18:39:07.454 2284-2653/com.nextcloud.talk2 W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2021-10-04 18:39:07.458 2284-2653/com.nextcloud.talk2 W/System.err:     at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
2021-10-04 18:39:07.462 2284-2653/com.nextcloud.talk2 W/System.err:     at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
2021-10-04 18:39:07.465 2284-2653/com.nextcloud.talk2 W/System.err:     at retrofit2.OkHttpCall.execute(OkHttpCall.java:204)
2021-10-04 18:39:07.468 2284-2653/com.nextcloud.talk2 W/System.err:     at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:46)
2021-10-04 18:39:07.471 2284-2653/com.nextcloud.talk2 W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:12284)
2021-10-04 18:39:07.475 2284-2653/com.nextcloud.talk2 W/System.err:     at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
2021-10-04 18:39:07.477 2284-2653/com.nextcloud.talk2 W/System.err:     at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:608)
2021-10-04 18:39:07.478 2284-2653/com.nextcloud.talk2 W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
2021-10-04 18:39:07.479 2284-2653/com.nextcloud.talk2 W/System.err: 	... 6 more
2021-10-04 18:39:07.607 2309-3481/? W/ActivityManager:   Force finishing activity com.nextcloud.talk2/com.nextcloud.talk.activities.MainActivity
```

**Comment by jakobroehrl** [comment]
I have exactly this problem with the latest versions of talk an NC.

**Comment by AndyScherzinger** [comment]
No activity since 2023 and both the media viewer and the upload path have been reworked since (#6429). Closing as stale — please open a fresh report if large videos still crash the app on 25.x.
