### ISSUE TITLE
App hangs on fresh install after local build

### ISSUE THREAD

**Issue by Grunthos** [nextcloud/talk-android#221]
Process:

- build in AS using latest AS and SDK etc matching build.gradle
- run app
- enter server
- enter user/password
- end up in white screen with progress circle running permanently.

Have send ADB log via email since it probably has private data etc

Pressing 'back' keys produces memory dumps from lead detecting software that is presumably in one of the many included 3rd party tools.

**Comment by mario** [comment]
Are you building a generic or gplay flavour?

**Comment by Grunthos** [comment]
Default build as per the instructions, which is genericDebug

On 28 June 2018 4:52:52 pm AEST, "Mario Đanić" <notifications@github.com> wrote:
>Are you building a generic or gplay flavour?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/nextcloud/talk-android/issues/221#issuecomment-400931454

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Grunthos** [comment]
Using gplayDebug results in a successful login followed by a memory dump by the leak detecting stuff.


On 28 June 2018 4:52:52 pm AEST, "Mario Đanić" <notifications@github.com> wrote:
>Are you building a generic or gplay flavour?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/nextcloud/talk-android/issues/221#issuecomment-400931454

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mario** [comment]
That is good. Notifications?

**Comment by mario** [comment]
@Grunthos ^_^

**Comment by Grunthos** [comment]
Still fails to register for notifications; the 400 error still being returned.

**Comment by Grunthos** [comment]
...but now my server is showing "client denied by server config". Progress.

**Comment by Grunthos** [comment]
OK. I hacked the server. The problem comes from PushController.php; specifically the following code is return the 400;
```
               $tokenId = $this->session->get('token-id');
                try {
                        $token = $this->tokenProvider->getTokenById($tokenId);
                } catch (InvalidTokenException $e) {
                        return new DataResponse(['message' => 'INVALID_SESSION_TOKEN'], Http::STATUS_BAD_REQUEST);
                }
```

**Comment by nickvergessen** [comment]
Password login can not use push notifications, because they get a new token id every time the session times out and so the proxy can not verify it anymore.

This has always been like that.

**Comment by Grunthos** [comment]
Probably good if the app warned users that notifications are not available then, and maybe advising on solution and offering to create a cert?

Or..why not generate a unique device id that is independent of session is and use that?


On 29 June 2018 12:36:12 am AEST, Joas Schilling <notifications@github.com> wrote:
>Password login can not use push notifications, because they get a new
>token id every time the session times out and so the proxy can not
>verify it anymore.
>
>This has always been like that.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/nextcloud/talk-android/issues/221#issuecomment-401056919

-- 
Sent from my Android device with K-9 Mail. Please excuse my spelling and brevity.

**Comment by mario** [comment]
@nickvergessen I know, but you can only use login flow with Talk which pretty much guarantees you get an app token. And this is what makes it strange.

**Comment by Grunthos** [comment]
So...does this leave me needing to investigate more; or is this something I should just leave alone for now.

If you do want me to investigate more, a hint as to where the "token" parameter is set/defined in the app would be helpful.

**Comment by nickvergessen** [comment]
Well best would be to debug this in place:
1. is token-id set in the session or is it empty. 
2. is the token in the database and what are it's values

**Comment by Grunthos** [comment]
@nickvergessen  Not sure of my way around app or server, but:

Re 1: tokenId is NOT set. Or at least  error_log('INVALID_SESSION_TOKEN: ', $tokenId ); results in just 'INVALID_SESSION_TOKEN:'

Re 2: do you mean server or app? And can you tell me a relevant query to check?

.

**Comment by Grunthos** [comment]
tokenId is set and exists in DB:

 select * from oc_authtoken where id = 15798;
15798|USER|USER|c3dc03f3a2c4b33851ca88e723d4969d|2x0NPcmNF7LCrEJ/|1cc5bf8678c62ab2133be9d42a4f16e37f1ef142f343fc5164b905f04741e6827b955142acc2cc94a8feceb39ea94a3ef2c98f3275f0f85f9d41a1bea8fba979|Asus ASUS_T00J (Nextcloud Talk)|376f75320682353fe51693ad8e4fc8ce9a5674d31bd74a94f50c098c79ccd1666353a7e5a3a6e107fb9c1e8420b0fbc8d9ef913f1a2059bcb7a3d332787f58a9|1|1530277996|1530277746|0||0

**Comment by Grunthos** [comment]
And here is the exception on the server when it tried to get the token:

Exception: 

#0 /srv/www/htdocs/nextcloud/apps/notifications/lib/Controller/PushController.php(112): OC\\Authentication\\Token\\DefaultTokenProvider->getTokenById(15798)\n
#1 [internal function]: OCA\\Notifications\\Controller\\PushController->registerDevice('2581914a7cf4aa3...', '-----BEGIN PUBL...', 'https://push-no...')\n
#2 /srv/www/htdocs/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(161): call_user_func_array(Array, Array)\n
#3 /srv/www/htdocs/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(91): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\Notifications\\Controller\\PushController), 'registerDevice')\n
#4 /srv/www/htdocs/nextcloud/lib/private/AppFramework/App.php(115): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Notifications\\Controller\\PushController), 'registerDevice')\n
#5 /srv/www/htdocs/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php(47): OC\\AppFramework\\App::main('OCA\\\\Notificatio...', 'registerDevice', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n
#6 [internal function]: OC\\AppFramework\\Routing\\RouteActionHandler->__invoke(Array)\n
#7 /srv/www/htdocs/nextcloud/lib/private/Route/Router.php(297): call_user_func(Object(OC\\AppFramework\\Routing\\RouteActionHandler), Array)\n
#8 /srv/www/htdocs/nextcloud/ocs/v1.php(78): OC\\Route\\Router->match('/ocsapp/apps/no...')\n
#9 /srv/www/htdocs/nextcloud/ocs/v2.php(24): require_once('/srv/www/htdocs...')\n#10 {main}

**Comment by Grunthos** [comment]
And a bit later I get and ExpiredTokenException:

\\nOC\\Authentication\\Token\\ExpiredTokenException in /srv/www/htdocs/nextcloud/lib/private/Authentication/Token/DefaultTokenProvider.php:191\n
Stack trace:\n
#0 /srv/www/htdocs/nextcloud/apps/notifications/lib/Controller/PushController.php(112): OC\\Authentication\\Token\\DefaultTokenProvider->getTokenById(15798)\n
#1 [internal function]: OCA\\Notifications\\Controller\\PushController->registerDevice('2581914a7cf4aa3...', '-----BEGIN PUBL...', 'https://push-no...')\n
#2 /srv/www/htdocs/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(161): call_user_func_array(Array, Array)\n
#3 /srv/www/htdocs/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(91): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\Notifications\\Controller\\PushController), 'registerDevice')\n
#4 /srv/www/htdocs/nextcloud/lib/private/AppFramework/App.php(115): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Notifications\\Controller\\PushController), 'registerDevice')\n
#5 /srv/www/htdocs/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php(47): OC\\AppFramework\\App::main('OCA\\\\Notificatio...', 'registerDevice', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n
#6 [internal function]: OC\\AppFramework\\Routing\\RouteActionHandler->__invoke(Array)\n
#7 /srv/www/htdocs/nextcloud/lib/private/Route/Router.php(297): call_user_func(Object(OC\\AppFramework\\Routing\\RouteActionHandler), Array)\n
#8 /srv/www/htdocs/nextcloud/ocs/v1.php(78): OC\\Route\\Router->match('/ocsapp/apps/no...')\n
#9 /srv/www/htdocs/nextcloud/ocs/v2.php(24): require_once('/srv/www/htdocs...')\n
#10 {main}\\n

**Comment by Grunthos** [comment]
My naive interpretation is that the token expiry of 0 is the problem.

**Comment by nickvergessen** [comment]
can you also copy the table headers? the columns seem to be in a different order than in a new install

**Comment by Grunthos** [comment]
@nickvergessen  See below:

           id = 15798
          uid = USER
   login_name = USER
     password = c3dc03f3a2c4b33851ca88e723d4969d|2x0NPcmNF7LCrEJ/|1cc5bf8678c62ab2133be9d42a4f16e37f1ef142f343fc5164b905f04741e6827b955142acc2cc94a8feceb39ea94a3ef2c98f3275f0f85f9d41a1bea8fba979
         name = Asus ASUS_T00J (Nextcloud Talk)
        token = 376f75320682353fe51693ad8e4fc8ce9a5674d31bd74a94f50c098c79ccd1666353a7e5a3a6e107fb9c1e8420b0fbc8d9ef913f1a2059bcb7a3d332787f58a9
         type = 1
last_activity = 1530280417
   last_check = 1530280202
     remember = 0
        scope =
      expires = 0

**Comment by Grunthos** [comment]
@nickvergessen @mario  ...so where does this leave us? Is there anything I can do?

**Comment by mario** [comment]
@nickvergessen is the main guy here @Grunthos and he has lots of work - he'll get back to this issue in time.

**Comment by mario** [comment]
@Grunthos could you set up a temporary new Nextcloud install and try with that?

**Comment by mario** [comment]
The original issue reported will be fixed in 2.2. As for why push doesn't work - most probably related to the server and I have no idea how to debug.
