### ISSUE TITLE
Starting a call from chat screen crashes

### ISSUE THREAD

**Issue by AlvaroBrey** [nextcloud/talk-android#2216]
## Steps to reproduce
1. Open a conversation
2. Tap on the call icon

### Expected behaviour
Call started

### Actual behaviour
```
2022-07-14 15:33:06.372 16865-16865/com.nextcloud.talk2 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.nextcloud.talk2, PID: 16865
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nextcloud.talk2/com.nextcloud.talk.activities.CallActivity}: java.lang.ClassCastException: com.nextcloud.talk.data.user.model.User cannot be cast to com.nextcloud.talk.models.database.UserEntity
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3635)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
     Caused by: java.lang.ClassCastException: com.nextcloud.talk.data.user.model.User cannot be cast to com.nextcloud.talk.models.database.UserEntity
        at com.nextcloud.talk.activities.CallActivity.onCreate(CallActivity.java:303)
        at android.app.Activity.performCreate(Activity.java:8051)
        at android.app.Activity.performCreate(Activity.java:8031)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3608)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.app.ActivityThread.main(ActivityThread.java:7839) 
        at java.lang.reflect.Method.invoke(Native Method)
```

## Device information

**Device:** any

**Android version:** any

**Talk version:** master

cc @AndyScherzinger

**Comment by AndyScherzinger** [comment]
@mahibi @AlvaroBrey fixed via #2219 and merged without review to ensure the next Alpha build works for calls again.
Feel free to review anyways if you like, any findings I can fix in a follow-up PR if there are any findings by you folks.
