### ISSUE TITLE
fail to open newly created conversation (ClassCastException UserEntity -> User)

### ISSUE THREAD

**Issue by mahibi** [nextcloud/talk-android#2220]
## Steps to reproduce
1. create new conversation via talk app

### Expected behaviour
new conversation opens

### Actual behaviour
conversation is created, but not opened
loading spinner keep on spinning

```
E/EventBus: Could not dispatch event: class com.nextcloud.talk.events.OpenConversationEvent to subscribing class class com.nextcloud.talk.controllers.ContactsController
    java.lang.ClassCastException: com.nextcloud.talk.models.database.UserEntity cannot be cast to com.nextcloud.talk.data.user.model.User
        at com.nextcloud.talk.controllers.ChatController.<init>(ChatController.kt:299)
        at com.nextcloud.talk.utils.ConductorRemapping.remapChatController(ConductorRemapping.kt:91)
        at com.nextcloud.talk.utils.ConductorRemapping.remapChatController(ConductorRemapping.kt:40)
        at com.nextcloud.talk.controllers.ContactsController.onMessageEvent(ContactsController.kt:734)
        at java.lang.reflect.Method.invoke(Native Method)
        at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:517)
        at org.greenrobot.eventbus.EventBus.postToSubscription(EventBus.java:444)
        at org.greenrobot.eventbus.EventBus.postSingleEventForEventType(EventBus.java:421)
        at org.greenrobot.eventbus.EventBus.postSingleEvent(EventBus.java:394)
        at org.greenrobot.eventbus.EventBus.post(EventBus.java:275)
        at com.nextcloud.talk.controllers.bottomsheet.OperationsMenuController.initiateConversation(OperationsMenuController.kt:727)
        at com.nextcloud.talk.controllers.bottomsheet.OperationsMenuController.access$initiateConversation(OperationsMenuController.kt:82)
        at com.nextcloud.talk.controllers.bottomsheet.OperationsMenuController$addUsersToConversation$1.onComplete(OperationsMenuController.kt:664)
        at io.reactivex.internal.operators.observable.ObservableRetryPredicate$RepeatObserver.onComplete(ObservableRetryPredicate.java:99)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.checkTerminated(ObservableObserveOn.java:287)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:193)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
        at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:124)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7590)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

**Comment by AndyScherzinger** [comment]
Fixed via #2221 also no-review merged to re.instate the feature for the next Alpha build, feel free to review the PR, I will fix any findings you might document then in a follow-up PR
