### ISSUE TITLE
New message notification don't open the conversation anymore

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/talk-android#2262]
Happens on master / 14.2.0 Alphas

**Comment by starypatyk** [comment]
@AndyScherzinger @mahibi I have looked briefly - the app just crashes...

```
07-29 21:49:31.423 21772 21772 D MainActivity: onStart: Activity: 61765747
07-29 21:49:31.423 21772 21772 D ConvListController: onAttach: Controller: 114672405 Activity: 61765747
07-29 21:49:31.445 21772 21772 D MainActivity: onNewIntent Activity: 61765747
07-29 21:49:31.446 21772 21772 D ChatController: init ChatController: 31247688
07-29 21:49:31.446 21772 21772 D ChatController:    roomToken = 4j47to4h
07-29 21:49:31.477 21772 21772 D ChatController: onViewBound: 31247688
07-29 21:49:31.479 21772 21772 D AndroidRuntime: Shutting down VM
--------- beginning of crash
07-29 21:49:31.480 21772 21772 E AndroidRuntime: FATAL EXCEPTION: main
07-29 21:49:31.480 21772 21772 E AndroidRuntime: Process: com.nextcloud.talk2, PID: 21772
07-29 21:49:31.480 21772 21772 E AndroidRuntime: java.lang.NullPointerException
07-29 21:49:31.480 21772 21772 E AndroidRuntime: 	at com.nextcloud.talk.controllers.ChatController.onViewBound(ChatController.kt:490)
07-29 21:49:31.480 21772 21772 E AndroidRuntime: 	at com.nextcloud.talk.controllers.base.NewBaseController$1.postCreateView(NewBaseController.kt:98)
07-29 21:49:31.480 21772 21772 E AndroidRuntime: 	at com.bluelinelabs.conductor.Controller.inflate(Controller.java:1102)
07-29 21:49:31.480 21772 21772 E AndroidRuntime: 	at com.bluelinelabs.conductor.ControllerChangeHandler.executeChange(ControllerChangeHandler.java:195)
07-29 21:49:31.480 21772 21772 E AndroidRuntime: 	at com.bluelinelabs.conductor.ControllerChangeHandler.executeChange(ControllerChangeHandler.java:159)
07-29 21:49:31.480 21772 21772 E AndroidRuntime: 	at com.bluelinelabs.conductor.Router.performControllerChange(Router.java:874)
07-29 21:49:31.480 21772 21772 E AndroidRuntime: 	at com.bluelinelabs.conductor.Router.performControllerChange(Router.java:832)
07-29 21:49:31.480 21772 21772 E AndroidRuntime: 	at com.bluelinelabs.conductor.Router.performControllerChange(Router.java:810)
07-29 21:49:31.480 21772 21772 E AndroidRuntime: 	at com.bluelinelabs.conductor.Router.pushController(Router.java:184)
07-29 21:49:31.480 21772 21772 E AndroidRuntime: 	at com.nextcloud.talk.utils.ConductorRemapping.remapChatController(ConductorRemapping.kt:83)
07-29 21:49:31.480 21772 21772 E AndroidRuntime: 	at com.nextcloud.talk.activities.MainActivity.onNewIntent(MainActivity.kt:356)
07-29 21:49:31.480 21772 21772 E AndroidRuntime: 	at android.app.Activity.performNewIntent(Activity.java:8009)
07-29 21:49:31.480 21772 21772 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1409)
07-29 21:49:31.480 21772 21772 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1422)
07-29 21:49:31.480 21772 21772 E AndroidRuntime: 	at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:3664)
07-29 21:49:31.480 21772 21772 E AndroidRuntime: 	at android.app.ActivityThread.handleNewIntent(ActivityThread.java:3676)
07-29 21:49:31.480 21772 21772 E AndroidRuntime: 	at android.app.servertransaction.NewIntentItem.execute(NewIntentItem.java:53)
07-29 21:49:31.480 21772 21772 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
07-29 21:49:31.480 21772 21772 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
07-29 21:49:31.480 21772 21772 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
07-29 21:49:31.480 21772 21772 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
07-29 21:49:31.480 21772 21772 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
07-29 21:49:31.480 21772 21772 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7656)
07-29 21:49:31.480 21772 21772 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-29 21:49:31.480 21772 21772 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
07-29 21:49:31.480 21772 21772 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

Seems to be related to: https://github.com/nextcloud/talk-android/commit/40f20c56d6b9e15009670441700ae7dfbeaf3c18
