### ISSUE TITLE
app crashes after hangup call

### ISSUE THREAD

**Issue by mahibi** [nextcloud/talk-android#2347]
### Steps to reproduce

1. start a call on android
2. join call on web
3. hangup on android

### Expected behaviour

app returns to conversation

### Actual behaviour

crash

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.nextcloud.talk2, PID: 5235
    java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.next(ArrayList.java:860)
        at com.nextcloud.talk.activities.CallActivity.hangup(CallActivity.java:1711)
        at com.nextcloud.talk.activities.CallActivity.lambda$initClickListeners$6$com-nextcloud-talk-activities-CallActivity(CallActivity.java:401)
        at com.nextcloud.talk.activities.CallActivity$$ExternalSyntheticLambda19.onClick(Unknown Source:2)
        at android.view.View.performClick(View.java:7185)
        at android.view.View.performClickInternal(View.java:7162)
        at android.view.View.access$3500(View.java:819)
        at android.view.View$PerformClick.run(View.java:27678)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7590)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

### Device brand and model

redmi note 7

### Android version

10

### Nextcloud Talk app version

15.0.0 Alpha 04

### Nextcloud server version

25.0.0 beta 3 (sermo)

**Comment by mahibi** [comment]
current code where it crashes:

```
        for (PeerConnectionWrapper wrapper : peerConnectionWrapperList) {
            endPeerConnection(wrapper.getSessionId(), false);
        }
```

replacing it with iterator doesn't work:

```
        Iterator<PeerConnectionWrapper> pcwIterator = peerConnectionWrapperList.iterator();
        while (pcwIterator.hasNext()) {
            PeerConnectionWrapper pcw = pcwIterator.next();
            endPeerConnection(pcw.getSessionId(), false);
        }
```
leads to the same crash.
