### ISSUE TITLE
File upload always fails for 1MB+ version 15.0.x

### ISSUE THREAD

**Issue by ASerbinski** [nextcloud/talk-android#2519]
### Steps to reproduce

1. Update NC Talk to version 15.0.x (15.0.0 F-Droid or 15.0.1 GPlay)
2. Attempt to upload file (take photo with HQ setting, or upload from device greater than 1 MB)

### Expected behaviour

The file should upload and become part of the conversation.

### Actual behaviour

Either-
1) Notification indicates failure.
2) Notification indicates upload freezes permanently at approximately 40%.

### Device brand and model

Pixel 3XL running factory Android 11 (GPlay), Pixel 6 Pro running GrapheneOS 13 (F-Droid), Pixel 7 Pro running GrapheneOS 13 (F-Droid)

### Android version

11 or 13

### Nextcloud Talk app version

15.0.0 F-Droid or 15.0.1 GPlay

### Nextcloud server version

24.0.6

### Talk version

14.0.5

**Comment by ASerbinski** [comment]
I also tried on Nextcloud 25.0.0 and same problems

**Comment by ASerbinski** [comment]
Logcat:

```
10-24 09:08:58.229 21616 21721 D UploadAndShareFilesWorker: starting chunked upload because size is 2586798
OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@ee75579, mPriority=0}
10-24 09:08:59.322 21616 21721 D ChunkedFileUploader: chunksOnServer: 0
10-24 09:08:59.323 21616 21721 D ChunkedFileUploader: missingChunks: 3
10-24 09:08:59.600  1974  2213 D LocalImageResolver: Couldn't use ImageDecoder for drawable, falling back to non-resized load.
10-24 09:08:59.603  1974  2213 D LocalImageResolver: Couldn't use ImageDecoder for drawable, falling back to non-resized load.
10-24 09:08:59.605  1974  2213 D LocalImageResolver: Couldn't use ImageDecoder for drawable, falling back to non-resized load.
10-24 09:08:59.654 21616 21721 D TrafficStats: tagSocket(82) with statsTag=0xffffffff, statsUid=-1
10-24 09:08:59.677  1700 20120 E NotificationService: Package enqueue rate is 6.560285. Shedding 0|com.nextcloud.talk2|19133664|null|10197. package=com.nextcloud.talk2
10-24 09:08:59.750 21616 21721 E ChunkedFileUploader: Something went wrong in ChunkedFileUploader
10-24 09:08:59.750 21616 21721 E ChunkedFileUploader: okhttp3.internal.http2.StreamResetException: stream was reset: NO_ERROR
10-24 09:08:59.750 21616 21721 E ChunkedFileUploader: 	at okhttp3.internal.http2.Http2Stream.checkOutNotClosed$okhttp(Http2Stream.kt:646)
10-24 09:08:59.750 21616 21721 E ChunkedFileUploader: 	at okhttp3.internal.http2.Http2Stream$FramingSink.emitFrame(Http2Stream.kt:557)
10-24 09:08:59.750 21616 21721 E ChunkedFileUploader: 	at okhttp3.internal.http2.Http2Stream$FramingSink.write(Http2Stream.kt:532)
10-24 09:08:59.750 21616 21721 E ChunkedFileUploader: 	at okio.ForwardingSink.write(ForwardingSink.kt:29)
10-24 09:08:59.750 21616 21721 E ChunkedFileUploader: 	at okhttp3.internal.connection.Exchange$RequestBodySink.write(Exchange.kt:218)
10-24 09:08:59.750 21616 21721 E ChunkedFileUploader: 	at okio.RealBufferedSink.close(RealBufferedSink.kt:279)
10-24 09:08:59.750 21616 21721 E ChunkedFileUploader: 	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:60)
10-24 09:08:59.750 21616 21721 E ChunkedFileUploader: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
10-24 09:08:59.750 21616 21721 E ChunkedFileUploader: 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
10-24 09:08:59.750 21616 21721 E ChunkedFileUploader: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
10-24 09:08:59.750 21616 21721 E ChunkedFileUploader: 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
10-24 09:08:59.750 21616 21721 E ChunkedFileUploader: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
10-24 09:08:59.750 21616 21721 E ChunkedFileUploader: 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
10-24 09:08:59.750 21616 21721 E ChunkedFileUploader: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
10-24 09:08:59.750 21616 21721 E ChunkedFileUploader: 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
10-24 09:08:59.750 21616 21721 E ChunkedFileUploader: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
10-24 09:08:59.750 21616 21721 E ChunkedFileUploader: 	at com.nextcloud.talk.dagger.modules.RestModule$HeadersInterceptor.intercept(RestModule.java:252)
10-24 09:08:59.750 21616 21721 E ChunkedFileUploader: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
10-24 09:08:59.750 21616 21721 E ChunkedFileUploader: 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
10-24 09:08:59.750 21616 21721 E ChunkedFileUploader: 	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
10-24 09:08:59.750 21616 21721 E ChunkedFileUploader: 	at at.bitfire.dav4jvm.DavResource$put$1.invoke(DavResource.kt:260)
10-24 09:08:59.750 21616 21721 E ChunkedFileUploader: 	at at.bitfire.dav4jvm.DavResource$put$1.invoke(DavResource.kt:245)
10-24 09:08:59.750 21616 21721 E ChunkedFileUploader: 	at at.bitfire.dav4jvm.DavResource.followRedirects$build(DavResource.kt:400)
10-24 09:08:59.750 21616 21721 E ChunkedFileUploader: 	at at.bitfire.dav4jvm.DavResource.put(DavResource.kt:245)
10-24 09:08:59.750 21616 21721 E ChunkedFileUploader: 	at at.bitfire.dav4jvm.DavResource.put$default(DavResource.kt:244)
10-24 09:08:59.750 21616 21721 E ChunkedFileUploader: 	at com.nextcloud.talk.upload.chunked.ChunkedFileUploader.uploadChunk(ChunkedFileUploader.kt:264)
10-24 09:08:59.750 21616 21721 E ChunkedFileUploader: 	at com.nextcloud.talk.upload.chunked.ChunkedFileUploader.upload(ChunkedFileUploader.kt:106)
10-24 09:08:59.750 21616 21721 E ChunkedFileUploader: 	at com.nextcloud.talk.jobs.UploadAndShareFilesWorker.doWork(UploadAndShareFilesWorker.kt:136)
10-24 09:08:59.750 21616 21721 E ChunkedFileUploader: 	at androidx.work.Worker$1.run(Worker.java:86)
10-24 09:08:59.750 21616 21721 E ChunkedFileUploader: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
10-24 09:08:59.750 21616 21721 E ChunkedFileUploader: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
10-24 09:08:59.750 21616 21721 E ChunkedFileUploader: 	at java.lang.Thread.run(Thread.java:1012)
10-24 09:08:59.750 21616 21721 E ChunkedFileUploader: 	Suppressed: okhttp3.internal.http2.StreamResetException: stream was reset: NO_ERROR
10-24 09:08:59.750 21616 21721 E ChunkedFileUploader: 		... 32 more
10-24 09:08:59.750 21616 21721 E UploadAndShareFilesWorker: Something went wrong when trying to upload file
10-24 09:08:59.752 21616 21716 I WM-WorkerWrapper: Worker result FAILURE for Work [ id=a4282ffa-c230-47e1-bc43-8b6fc0c99bb1, tags={ com.nextcloud.talk.jobs.UploadAndShareFilesWorker } ]
```

**Comment by ASerbinski** [comment]
Apache log;

```
142.112.15.192 - - [24/Oct/2022:09:21:16 -0400] [215 ms] "HEAD /remote.php/dav/files/adam/Talk/95804d_95d7809702554dd39f75d7db7403198b~mv2.jpg HTTP/2.0" 404 - "-" "Mozilla/5.0 (Android) Nextcloud-Talk v15.0.1"
142.112.15.192 - - [24/Oct/2022:09:21:16 -0400] [55 ms] "MKCOL /remote.php/dav/uploads/adam/df1a9a16332583895960a9866dac72c5 HTTP/2.0" 401 557 "-" "Mozilla/5.0 (Android) Nextcloud-Talk v15.0.1"
142.112.15.192 - - [24/Oct/2022:09:21:16 -0400] [231 ms] "MKCOL /remote.php/dav/uploads/adam/df1a9a16332583895960a9866dac72c5 HTTP/2.0" 201 - "-" "Mozilla/5.0 (Android) Nextcloud-Talk v15.0.1"
142.112.15.192 - - [24/Oct/2022:09:21:16 -0400] [57 ms] "PROPFIND /remote.php/dav/uploads/adam/df1a9a16332583895960a9866dac72c5 HTTP/2.0" 401 557 "-" "Mozilla/5.0 (Android) Nextcloud-Talk v15.0.1"
142.112.15.192 - - [24/Oct/2022:09:21:16 -0400] [259 ms] "PROPFIND /remote.php/dav/uploads/adam/df1a9a16332583895960a9866dac72c5 HTTP/2.0" 207 375 "-" "Mozilla/5.0 (Android) Nextcloud-Talk v15.0.1"
142.112.15.192 - - [24/Oct/2022:09:21:17 -0400] [60 ms] "PUT /remote.php/dav/uploads/adam/df1a9a16332583895960a9866dac72c5/0000000000000000-0000000001023999 HTTP/2.0" 401 557 "-" "Mozilla/5.0 (Android) Nextcloud-Talk v15.0.1"
142.112.15.192 - - [24/Oct/2022:09:21:16 -0400] [485 ms] "GET /ocs/v2.php/apps/spreed/api/v4/room?includeStatus=true HTTP/2.0" 200 1019 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:105.0) Gecko/20100101 Firefox/105.0"
142.112.15.192 - - [24/Oct/2022:09:21:17 -0400] [53 ms] "PUT /remote.php/dav/uploads/adam/df1a9a16332583895960a9866dac72c5/0000000000000000-0000000001023999 HTTP/2.0" 401 557 "-" "Mozilla/5.0 (Android) Nextcloud-Talk v15.0.1"
```

**Comment by mahibi** [comment]
thanks for the logs @ASerbinski 
we will have a look!

**Comment by TheElizir** [comment]
Same problem here. We're usually using Talk to send some pictures within groups but since the update 5 days ago we got the same behaviour when trying to send a file or picture.

**Device brand and model**
OnePlus 8 and Xiaomi 12

**Android version**
12

**Nextcloud Talk app version**
15.0.1 GPlay

**Nextcloud server version**
23.0.2.1

**Talk version**
13.0.9

**Comment by starypatyk** [comment]
Same here. I have also noticed that when the error notification is shown, it is not possible to dismiss the notification.

I suspect that **setOngoing(false)** call should be added here:
https://github.com/nextcloud/talk-android/blob/0f9fc7c306df6087d6160c41806fbbdaf08a4e42/app/src/main/java/com/nextcloud/talk/jobs/UploadAndShareFilesWorker.kt#L261

I have not yet found a way to get rid of these notifications. Restarting the app did not help. :disappointed: 

Not sure how many people are going to be affected by this issue, but it might be worth considering clearing such stale notifications at some point - e.g. when starting the application.

**Comment by mahibi** [comment]
thank you for the PR @starypatyk !
can you test [this version](https://github.com/nextcloud/talk-android/pull/2532#issuecomment-1294140998) and let me know if this also fixes the problem for you @ASerbinski @TheElizir ?

**Comment by ASerbinski** [comment]
@mahibi It seems to solve the immediate problem and allows uploads to complete as expected.

However, it seems a bit hacky to revert to an older protocol version. In some circumstances, I would anticipate the potential for disabling anything less than http/2 altogether, and this will probably become more of an issue with time.

I'd say accept this for now as an emergency fix, but at some point it needs to be fixed for http/2.

**Comment by mahibi** [comment]
i agree @ASerbinski this is not the best solution for the long term but i merged this now to become a hotfix for 15.0.2.
thank you @starypatyk :+1: 
and thank you @ASerbinski for the logs again :+1:

**Comment by starypatyk** [comment]
@mahibi @ASerbinski - fully agree with your assessment that this is not good in the long run - only a temporary hotfix until we understand the real cause. :wink: 

https://geek-and-poke.com/geekandpoke/2009/7/6/geeks.html

**Comment by madsmki** [comment]
I have exact same issue.

Android 12
Talk App v18.1.0
Nextcloud server 28.0.2
PHP 8.2

I am new to this forum. Should I file a new issue or will this one be reopened?
