### ISSUE TITLE
Crashes because of NPE in ControllerViewBindingDelegate

### ISSUE THREAD

**Issue by mahibi** [nextcloud/talk-android#2666]
### Steps to reproduce

can happen randomly

### Expected behaviour

no crash

### Actual behaviour

see NPE's in gplay console.

examples:

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.nextcloud.talk2, PID: 5251
    java.lang.NullPointerException
        at com.nextcloud.talk.controllers.util.ControllerViewBindingDelegate.getValue(ControllerViewBindingDelegate.kt:47)
        at com.nextcloud.talk.controllers.AccountVerificationController.getBinding(AccountVerificationController.kt:83)
        at com.nextcloud.talk.controllers.AccountVerificationController.onMessageEvent$lambda$0(AccountVerificationController.kt:383)
        at com.nextcloud.talk.controllers.AccountVerificationController.$r8$lambda$IrbsuB1hlVctlTGw6Cl6z1cfNI4(Unknown Source:0)
        at com.nextcloud.talk.controllers.AccountVerificationController$$ExternalSyntheticLambda1.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7590)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
I/okhttp.OkHttpClient: <-- 200 OK https://push-notifications.nextcloud.com/devices (77ms)
I/okhttp.OkHttpClient: Server: nginx
I/okhttp.OkHttpClient: Date: Wed, 04 Jan 2023 13:57:29 GMT
I/okhttp.OkHttpClient: Content-Type: text/plain; charset=utf-8
I/okhttp.OkHttpClient: Content-Length: 1
I/okhttp.OkHttpClient: Connection: keep-alive
I/okhttp.OkHttpClient: X-Content-Type-Options: nosniff
I/okhttp.OkHttpClient: Strict-Transport-Security: max-age=15768000
I/okhttp.OkHttpClient: 
I/okhttp.OkHttpClient: <-- END HTTP (1-byte body)
```

startAudioRecording:

```

Exception java.lang.NullPointerException:
  at com.nextcloud.talk.controllers.util.ControllerViewBindingDelegate.getValue (ControllerViewBindingDelegate.kt:47)
  at com.nextcloud.talk.controllers.ChatController.getBinding (ChatController.kt:230)
  at com.nextcloud.talk.controllers.ChatController.startAudioRecording (ChatController.kt:1160)
  at com.nextcloud.talk.controllers.ChatController.access$startAudioRecording (ChatController.kt:216)
  at com.nextcloud.talk.controllers.ChatController$onViewBound$10.onTouch (ChatController.kt:800)
  at android.view.View.dispatchTouchEvent (View.java:15072)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:3923)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:3538)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:3923)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:3538)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:3923)
```

showUserProfile:
```
Exception java.lang.NullPointerException:
  at com.nextcloud.talk.controllers.util.ControllerViewBindingDelegate.getValue (ControllerViewBindingDelegate.kt:47)
  at com.nextcloud.talk.controllers.ProfileController.getBinding (ProfileController.kt:99)
  at com.nextcloud.talk.controllers.ProfileController.showUserProfile (ProfileController.kt:286)
  at com.nextcloud.talk.controllers.ProfileController.access$showUserProfile (ProfileController.kt:96)
  at com.nextcloud.talk.controllers.ProfileController$onAttach$5.onNext (ProfileController.kt:245)
  at com.nextcloud.talk.controllers.ProfileController$onAttach$5.onNext (ProfileController.kt:238)
```

**Comment by mahibi** [comment]
TODO; check where 

```
try{
   ...
} catch (npe: NullPointerException) {
    // view binding can be null
    // since this is called asynchronously and UI might have been destroyed in the meantime
    Log.i(TAG, "UI destroyed - view binding already gone")
}
```

can help and where other "solutions" are needed..
