### ISSUE TITLE
upload failures

### ISSUE THREAD

**Issue by mahibi** [nextcloud/talk-android#2809]
### Steps to reproduce

failure upload file from android talk.

might be server config related (internal nextcloud testserver..)

# normal upload

```
2023-03-01 17:19:49.268  1837-2250  okhttp.OkHttpClient     com.nextcloud.talk2                  I  --> HEAD https://XXXXXXXXXXXXX.com/remote.php/dav/files/marcel2/Talk/Screenshot_2023-01-30-11-33-06-756_com.miui.home.jpg
2023-03-01 17:19:49.268  1837-2250  okhttp.OkHttpClient     com.nextcloud.talk2                  I  Authorization: ██
2023-03-01 17:19:49.269  1837-2250  okhttp.OkHttpClient     com.nextcloud.talk2                  I  User-Agent: Mozilla/5.0 (Android) Nextcloud-Talk v16.1.0 Alpha 02
2023-03-01 17:19:49.269  1837-2250  okhttp.OkHttpClient     com.nextcloud.talk2                  I  Accept: application/json
2023-03-01 17:19:49.269  1837-2250  okhttp.OkHttpClient     com.nextcloud.talk2                  I  OCS-APIRequest: true
2023-03-01 17:19:49.269  1837-2250  okhttp.OkHttpClient     com.nextcloud.talk2                  I  --> END HEAD
2023-03-01 17:19:49.464  1837-2250  okhttp.OkHttpClient     com.nextcloud.talk2                  I  <-- 500 https://XXXXXXXXXXXXX.com/remote.php/dav/files/marcel2/Talk/Screenshot_2023-01-30-11-33-06-756_com.miui.home.jpg (193ms)
2023-03-01 17:19:49.464  1837-2250  okhttp.OkHttpClient     com.nextcloud.talk2                  I  server: nginx/1.18.0 (Ubuntu)
2023-03-01 17:19:49.464  1837-2250  okhttp.OkHttpClient     com.nextcloud.talk2                  I  date: Wed, 01 Mar 2023 16:19:49 GMT
2023-03-01 17:19:49.465  1837-2250  okhttp.OkHttpClient     com.nextcloud.talk2                  I  content-type: application/xml; charset=utf-8
2023-03-01 17:19:49.465  1837-2250  okhttp.OkHttpClient     com.nextcloud.talk2                  I  set-cookie: cookie_test=test; expires=Wed, 01-Mar-2023 17:19:49 GMT; Max-Age=3600
2023-03-01 17:19:49.465  1837-2250  okhttp.OkHttpClient     com.nextcloud.talk2                  I  content-security-policy: default-src 'none';
2023-03-01 17:19:49.465  1837-2250  okhttp.OkHttpClient     com.nextcloud.talk2                  I  <-- END HTTP
2023-03-01 17:19:49.472  1837-2248  UploadAndS...ilesWorker com.nextcloud.talk2                  D  starting normal upload (not chunked)
2023-03-01 17:19:49.494  1837-2237  okhttp.OkHttpClient     com.nextcloud.talk2                  I  --> PUT https://XXXXXXXXXXXXX.com/remote.php/dav/files/marcel2/Talk/Screenshot_2023-01-30-11-33-06-756_com.miui.home.jpg
2023-03-01 17:19:49.494  1837-2237  okhttp.OkHttpClient     com.nextcloud.talk2                  I  Content-Type: application/octet-stream
2023-03-01 17:19:49.495  1837-2237  okhttp.OkHttpClient     com.nextcloud.talk2                  I  Content-Length: 308418
2023-03-01 17:19:49.495  1837-2237  okhttp.OkHttpClient     com.nextcloud.talk2                  I  Authorization: ██
2023-03-01 17:19:49.496  1837-2237  okhttp.OkHttpClient     com.nextcloud.talk2                  I  User-Agent: Mozilla/5.0 (Android) Nextcloud-Talk v16.1.0 Alpha 02
2023-03-01 17:19:49.496  1837-2237  okhttp.OkHttpClient     com.nextcloud.talk2                  I  Accept: application/json
2023-03-01 17:19:49.496  1837-2237  okhttp.OkHttpClient     com.nextcloud.talk2                  I  OCS-APIRequest: true
2023-03-01 17:19:49.499  1837-2237  okhttp.OkHttpClient     com.nextcloud.talk2                  I  --> END PUT (binary 308418-byte body omitted)
2023-03-01 17:19:50.104  1837-2237  okhttp.OkHttpClient     com.nextcloud.talk2                  I  <-- HTTP FAILED: okhttp3.internal.http2.StreamResetException: stream was reset: NO_ERROR
2023-03-01 17:19:50.118  1837-2248  UploadAndS...ilesWorker com.nextcloud.talk2                  E  Something went wrong when trying to upload file
                                                                                                    java.lang.RuntimeException: okhttp3.internal.http2.StreamResetException: stream was reset: NO_ERROR
                                                                                                    	at io.reactivex.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:46)
                                                                                                    	at io.reactivex.internal.observers.BlockingBaseObserver.blockingGet(BlockingBaseObserver.java:80)
                                                                                                    	at io.reactivex.Observable.blockingFirst(Observable.java:5120)
                                                                                                    	at com.nextcloud.talk.jobs.UploadAndShareFilesWorker.doWork(UploadAndShareFilesWorker.kt:156)
                                                                                                    	at androidx.work.Worker$1.run(Worker.java:86)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                    	at java.lang.Thread.run(Thread.java:919)
                                                                                                    Caused by: okhttp3.internal.http2.StreamResetException: stream was reset: NO_ERROR
                                                                                                    	at okhttp3.internal.http2.Http2Stream.checkOutNotClosed$okhttp(Http2Stream.kt:646)
                                                                                                    	at okhttp3.internal.http2.Http2Stream$FramingSink.emitFrame(Http2Stream.kt:557)
                                                                                                    	at okhttp3.internal.http2.Http2Stream$FramingSink.write(Http2Stream.kt:532)
                                                                                                    	at okio.ForwardingSink.write(ForwardingSink.kt:29)
                                                                                                    	at okhttp3.internal.connection.Exchange$RequestBodySink.write(Exchange.kt:218)
                                                                                                    	at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.kt:255)
                                                                                                    	at okio.RealBufferedSink.write(RealBufferedSink.kt:185)
                                                                                                    	at okhttp3.RequestBody$Companion$toRequestBody$2.writeTo(RequestBody.kt:152)
                                                                                                    	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:59)
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                                                                                                    	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                                                                                                    	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                                                                                                    	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                                                                                                    	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                                                                                                    	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:221)
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                                                                                                    	at com.nextcloud.talk.dagger.modules.RestModule$HeadersInterceptor.intercept(RestModule.java:252)
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                                                                                                    	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
                                                                                                    	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
                                                                                                    	at retrofit2.OkHttpCall.execute(OkHttpCall.java:204)
                                                                                                    	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:46)
                                                                                                    	at io.reactivex.Observable.subscribe(Observable.java:12284)
                                                                                                    	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
                                                                                                    	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:608)
                                                                                                    	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
                                                                                                    	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                                                                                    	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
                                                                                                    	at java.lang.Thread.run(Thread.java:919) 
                                                                                                    	Suppressed: okhttp3.internal.http2.StreamResetException: stream was reset: NO_ERROR
                                                                                                    		... 36 more
```

# chunked upload

```
2023-03-01 17:31:52.507  4223-4667  okhttp.OkHttpClient     com.nextcloud.talk2                  I  --> GET https://XXXXXXXXXXX.com/ocs/v2.php/apps/spreed/api/v1/chat/3853979093?lastKnownMessageId=53918&includeLastKnown=0&limit=100&setReadMarker=0&timeout=30&lookIntoFuture=1
2023-03-01 17:31:52.508  4223-4667  okhttp.OkHttpClient     com.nextcloud.talk2                  I  Authorization: ██
2023-03-01 17:31:52.508  4223-4667  okhttp.OkHttpClient     com.nextcloud.talk2                  I  User-Agent: Mozilla/5.0 (Android) Nextcloud-Talk v16.1.0 Alpha 02
2023-03-01 17:31:52.509  4223-4667  okhttp.OkHttpClient     com.nextcloud.talk2                  I  Accept: application/json
2023-03-01 17:31:52.509  4223-4667  okhttp.OkHttpClient     com.nextcloud.talk2                  I  OCS-APIRequest: true
2023-03-01 17:31:52.510  4223-4667  okhttp.OkHttpClient     com.nextcloud.talk2                  I  --> END GET
2023-03-01 17:31:52.572  4223-4670  okhttp.OkHttpClient     com.nextcloud.talk2                  I  <-- 500 https://XXXXXXXXXXX.com/remote.php/dav/files/marcel2/Talk/Videoaufnahme%20von%202023-03-01%2017-31-24.mp4 (145ms)
2023-03-01 17:31:52.572  4223-4670  okhttp.OkHttpClient     com.nextcloud.talk2                  I  server: nginx/1.18.0 (Ubuntu)
2023-03-01 17:31:52.572  4223-4670  okhttp.OkHttpClient     com.nextcloud.talk2                  I  date: Wed, 01 Mar 2023 16:31:52 GMT
2023-03-01 17:31:52.572  4223-4670  okhttp.OkHttpClient     com.nextcloud.talk2                  I  content-type: application/xml; charset=utf-8
2023-03-01 17:31:52.573  4223-4670  okhttp.OkHttpClient     com.nextcloud.talk2                  I  expires: Thu, 19 Nov 1981 08:52:00 GMT
2023-03-01 17:31:52.573  4223-4670  okhttp.OkHttpClient     com.nextcloud.talk2                  I  cache-control: no-store, no-cache, must-revalidate
2023-03-01 17:31:52.573  4223-4670  okhttp.OkHttpClient     com.nextcloud.talk2                  I  pragma: no-cache
2023-03-01 17:31:52.573  4223-4670  okhttp.OkHttpClient     com.nextcloud.talk2                  I  content-security-policy: default-src 'none';
2023-03-01 17:31:52.574  4223-4670  okhttp.OkHttpClient     com.nextcloud.talk2                  I  <-- END HTTP
2023-03-01 17:31:52.577  4223-4658  UploadAndS...ilesWorker com.nextcloud.talk2                  D  starting chunked upload because size is 33656912
2023-03-01 17:31:52.852  4223-4249  nextcloud.talk          com.nextcloud.talk2                  I  Background young concurrent copying GC freed 167693(7733KB) AllocSpace objects, 10(360KB) LOS objects, 38% free, 12MB/20MB, paused 1.211ms total 105.222ms
2023-03-01 17:31:52.899  4223-4658  okhttp.OkHttpClient     com.nextcloud.talk2                  I  --> MKCOL https://XXXXXXXXXXX.com/remote.php/dav/uploads/marcel2/a3790c93ca0c30566472fd0575b56bee
2023-03-01 17:31:52.900  4223-4658  okhttp.OkHttpClient     com.nextcloud.talk2                  I  User-Agent: Mozilla/5.0 (Android) Nextcloud-Talk v16.1.0 Alpha 02
2023-03-01 17:31:52.900  4223-4658  okhttp.OkHttpClient     com.nextcloud.talk2                  I  Accept: application/json
2023-03-01 17:31:52.901  4223-4658  okhttp.OkHttpClient     com.nextcloud.talk2                  I  OCS-APIRequest: true
2023-03-01 17:31:52.901  4223-4658  okhttp.OkHttpClient     com.nextcloud.talk2                  I  --> END MKCOL
2023-03-01 17:31:53.379  4223-4658  okhttp.OkHttpClient     com.nextcloud.talk2                  I  <-- 500 Internal Server Error https://XXXXXXXXXXX.com/remote.php/dav/uploads/marcel2/a3790c93ca0c30566472fd0575b56bee (476ms)
2023-03-01 17:31:53.379  4223-4658  okhttp.OkHttpClient     com.nextcloud.talk2                  I  Server: nginx/1.18.0 (Ubuntu)
2023-03-01 17:31:53.379  4223-4658  okhttp.OkHttpClient     com.nextcloud.talk2                  I  Date: Wed, 01 Mar 2023 16:31:53 GMT
2023-03-01 17:31:53.379  4223-4658  okhttp.OkHttpClient     com.nextcloud.talk2                  I  Content-Type: application/xml; charset=utf-8
2023-03-01 17:31:53.380  4223-4658  okhttp.OkHttpClient     com.nextcloud.talk2                  I  Transfer-Encoding: chunked
2023-03-01 17:31:53.380  4223-4658  okhttp.OkHttpClient     com.nextcloud.talk2                  I  Connection: keep-alive
2023-03-01 17:31:53.380  4223-4658  okhttp.OkHttpClient     com.nextcloud.talk2                  I  Expires: Thu, 19 Nov 1981 08:52:00 GMT
2023-03-01 17:31:53.380  4223-4658  okhttp.OkHttpClient     com.nextcloud.talk2                  I  Cache-Control: no-store, no-cache, must-revalidate
2023-03-01 17:31:53.380  4223-4658  okhttp.OkHttpClient     com.nextcloud.talk2                  I  Pragma: no-cache
2023-03-01 17:31:53.381  4223-4658  okhttp.OkHttpClient     com.nextcloud.talk2                  I  Content-Security-Policy: default-src 'none';
2023-03-01 17:31:53.385  4223-4658  okhttp.OkHttpClient     com.nextcloud.talk2                  I  <?xml version="1.0" encoding="utf-8"?>
2023-03-01 17:31:53.385  4223-4658  okhttp.OkHttpClient     com.nextcloud.talk2                  I  <d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
2023-03-01 17:31:53.385  4223-4658  okhttp.OkHttpClient     com.nextcloud.talk2                  I    <s:exception>Exception</s:exception>
2023-03-01 17:31:53.385  4223-4658  okhttp.OkHttpClient     com.nextcloud.talk2                  I    <s:message>Could not load OCA\Photos\Sabre\PropFindPlugin</s:message>
2023-03-01 17:31:53.385  4223-4658  okhttp.OkHttpClient     com.nextcloud.talk2                  I  </d:error>
2023-03-01 17:31:53.385  4223-4658  okhttp.OkHttpClient     com.nextcloud.talk2                  I  <-- END HTTP (219-byte body)
2023-03-01 17:31:53.400  4223-4658  ChunkedFileUploader     com.nextcloud.talk2                  E  Something went wrong in ChunkedFileUploader
                                                                                                    java.io.IOException: failed to create folder
                                                                                                    	at com.nextcloud.talk.upload.chunked.ChunkedFileUploader.createFolder(ChunkedFileUploader.kt:134)
                                                                                                    	at com.nextcloud.talk.upload.chunked.ChunkedFileUploader.upload(ChunkedFileUploader.kt:98)
                                                                                                    	at com.nextcloud.talk.jobs.UploadAndShareFilesWorker.doWork(UploadAndShareFilesWorker.kt:138)
                                                                                                    	at androidx.work.Worker$1.run(Worker.java:86)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                    	at java.lang.Thread.run(Thread.java:919)
                                                                                                    Caused by: at.bitfire.dav4jvm.exception.HttpException: HTTP 500 Internal Server Error
                                                                                                    	at at.bitfire.dav4jvm.DavResource.checkStatus(DavResource.kt:384)
                                                                                                    	at at.bitfire.dav4jvm.DavResource.checkStatus(DavResource.kt:358)
                                                                                                    	at at.bitfire.dav4jvm.DavResource.mkCol(DavResource.kt:195)
                                                                                                    	at com.nextcloud.talk.upload.chunked.ChunkedFileUploader.createFolder(ChunkedFileUploader.kt:121)
                                                                                                    	at com.nextcloud.talk.upload.chunked.ChunkedFileUploader.upload(ChunkedFileUploader.kt:98) 
                                                                                                    	at com.nextcloud.talk.jobs.UploadAndShareFilesWorker.doWork(UploadAndShareFilesWorker.kt:138) 
                                                                                                    	at androidx.work.Worker$1.run(Worker.java:86) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
                                                                                                    	at java.lang.Thread.run(Thread.java:919) 
2023-03-01 17:31:53.400  4223-4658  UploadAndS...ilesWorker com.nextcloud.talk2                  E  Something went wrong when trying to upload file
```

### Nextcloud Talk app version
all

**Comment by SystemKeeper** [comment]
@nickvergessen

**Comment by nickvergessen** [comment]
Should be fixed now

**Comment by SystemKeeper** [comment]
Confirmed for iOS

**Comment by jtxnn678** [comment]
same, "Upload failed" for iPhone13.
It was working before, suddenly upload failed.

**Comment by mahibi** [comment]
> same, "Upload failed" for iPhone13. It was working before, suddenly upload failed.

for iOS, please create issues at https://github.com/nextcloud/talk-ios/issues
