### ISSUE TITLE
The Nextcloud Talk Android app crashed during a video call

### ISSUE THREAD

**Issue by Doraemon-byte** [nextcloud/talk-android#2947]
### Steps to reproduce

1.Enter a session in the APP
2.Enable video call
3.Description During a video call, five users frequently enter or exit the video call (Because they lost the connection after entering the video call and tried to reconnect to the call)

### Expected behaviour

app works normally

### Actual behaviour

When they frequently join/drop out of a call, it causes the talk software to crash 90% of the time for the normal person

### Device brand and model

Xiaomi Redmi K40

### Android version

13

### Nextcloud Talk app version

16.0.0

### Nextcloud server version

26.0.0

### Talk version

16.0.2

### Custom Signaling server configured

None

### Custom TURN server configured

None

### Custom STUN server configured

None

**Comment by Doraemon-byte** [comment]
After repeated Android crashes we get the following log summary:
```
java.lang.RuntimeException: android.opengl.GLException: Failed to create EGL context: 0x3000
	at org.webrtc.EglBase14Impl.createEglContext(EglBase14Impl.java:268)
	at org.webrtc.EglBase14Impl.<init>(EglBase14Impl.java:63)
	at org.webrtc.EglBase$-CC.createEgl14(EglBase.java:213)
	at org.webrtc.EglBase$-CC.create(EglBase.java:156)
	at org.webrtc.EglRenderer.lambda$init$0$org-webrtc-EglRenderer(EglRenderer.java:241)
	at org.webrtc.EglRenderer$$ExternalSyntheticLambda7.run(Unknown Source:6)
	at org.webrtc.ThreadUtils$4.call(ThreadUtils.java:199)
	at org.webrtc.ThreadUtils$4.call(ThreadUtils.java:196)
	at org.webrtc.ThreadUtils$3.run(ThreadUtils.java:173)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at org.webrtc.EglRenderer$HandlerWithExceptionCallback.dispatchMessage(EglRenderer.java:103)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.os.HandlerThread.run(HandlerThread.java:67)
	at org.webrtc.ThreadUtils.invokeAtFrontUninterruptibly(ThreadUtils.java:184)
	at org.webrtc.ThreadUtils.invokeAtFrontUninterruptibly(ThreadUtils.java:196)
	at org.webrtc.EglRenderer.init(EglRenderer.java:232)
	at org.webrtc.EglRenderer.init(EglRenderer.java:259)
	at org.webrtc.SurfaceEglRenderer.init(SurfaceEglRenderer.java:61)
	at org.webrtc.SurfaceViewRenderer.init(SurfaceViewRenderer.java:87)
	at org.webrtc.SurfaceViewRenderer.init(SurfaceViewRenderer.java:71)
	at com.nextcloud.talk.activities.CallActivity.initSelfVideoView(CallActivity.java:840)
	at com.nextcloud.talk.activities.CallActivity.initViews(CallActivity.java:809)
	at com.nextcloud.talk.activities.CallActivity.updateUiForNormalMode(CallActivity.java:3087)
	at com.nextcloud.talk.activities.CallActivity.onPictureInPictureModeChanged(CallActivity.java:3022)
	at android.app.Activity.dispatchPictureInPictureModeChanged(Activity.java:8867)
	at android.app.ActivityThread.handleWindowingModeChangeIfNeeded(ActivityThread.java:6264)
	at android.app.ActivityThread.performActivityConfigurationChanged(ActivityThread.java:6079)
	at android.app.ActivityThread.performConfigurationChangedForActivity(ActivityThread.java:6056)
	at android.app.ActivityThread.handleActivityConfigurationChanged(ActivityThread.java:6401)
	at android.app.servertransaction.ActivityConfigurationChangeItem.execute(ActivityConfigurationChangeItem.java:53)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2389)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8261)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
Caused by: android.opengl.GLException: Failed to create EGL context: 0x3000
	at org.webrtc.EglBase14Impl.createEglContext(EglBase14Impl.java:268)
	at org.webrtc.EglBase14Impl.<init>(EglBase14Impl.java:63)
	at org.webrtc.EglBase$-CC.createEgl14(EglBase.java:213)
	at org.webrtc.EglBase$-CC.create(EglBase.java:156)
	at org.webrtc.EglRenderer.lambda$init$0$org-webrtc-EglRenderer(EglRenderer.java:241)
	at org.webrtc.EglRenderer$$ExternalSyntheticLambda7.run(Unknown Source:6)
	at org.webrtc.ThreadUtils$4.call(ThreadUtils.java:199)
	at org.webrtc.ThreadUtils$4.call(ThreadUtils.java:196)
	at org.webrtc.ThreadUtils$3.run(ThreadUtils.java:173)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at org.webrtc.EglRenderer$HandlerWithExceptionCallback.dispatchMessage(EglRenderer.java:103)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.os.HandlerThread.run(HandlerThread.java:67)

```

**Comment by Doraemon-byte** [comment]
@mahibi Hello, this is my first time providing feedback here. It has been three weeks since the release, but it has not been classified yet. I am not sure where I did the wrong thing. I saw that you were dealing with some issues and then @ you. Please understand

**Comment by mahibi** [comment]
Thank you for posting the log @Doraemon-byte :+1: 
i will look into this when i find some time.

i remember i saw this error already in the past and i think it was also a Xiaomi, so this might be related.

**Comment by Doraemon-byte** [comment]
There is a different error log and the runtime information is still the same.
This is the error log:
```
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Redmi/alioth/alioth:13/TKQ1.220829.002/V14.0.23.4.17.DEV:user/release-keys'
Revision: '0'
ABI: 'arm64'
Timestamp: 2023-06-11 22:22:33.425037441+0800
Process uptime: 509s
ZygotePid: 1940691768
Cmdline: com.nextcloud.talk2
pid: 24433, tid: 29092, name: EncoderQueue -  >>> com.nextcloud.talk2 <<<
uid: 10323
signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
    x0  0000000000000000  x1  00000000000071a4  x2  0000000000000006  x3  0000006e1f89f910
    x4  636064675e686d69  x5  636064675e686d69  x6  636064675e686d69  x7  7f7f7f7f7f7f7f7f
    x8  00000000000000f0  x9  00000070314abcb0  x10 0000000000000001  x11 0000007031520748
    x12 0000006e1f89e220  x13 00000000000000e7  x14 0000006e1f89e2d0  x15 0000000034155555
    x16 000000703158ba70  x17 00000070315643d0  x18 0000006e1f756000  x19 0000000000005f71
    x20 00000000000071a4  x21 00000000ffffffff  x22 0000006ef9a55c8d  x23 0000000000004586
    x24 aaaaaaaaaaaaaaaa  x25 0000006efa3661a8  x26 0000000000000500  x27 000000000000012c
    x28 000000000000003c  x29 0000006e1f89f990
    lr  00000070315116c8  sp  0000006e1f89f8f0  pc  00000070315116f4  pst 0000000000001000
backtrace:
      #00 pc 000000000008d6f4  /apex/com.android.runtime/lib64/bionic/libc.so (abort+168) (BuildId: 2bb0d7188c0db2e8beecb24658ba9d71)
      #01 pc 00000000003fe5c0  /data/app/~~FRx4oZtvxOdKDK8iXc5cjw==/com.nextcloud.talk2-S2k0HXUo_FoaiHlotoj9sA==/base.apk!libjingle_peerconnection_so.so (BuildId: 234e35823a23d295)
      #02 pc 00000000003fec0c  /data/app/~~FRx4oZtvxOdKDK8iXc5cjw==/com.nextcloud.talk2-S2k0HXUo_FoaiHlotoj9sA==/base.apk!libjingle_peerconnection_so.so (BuildId: 234e35823a23d295)
      #03 pc 00000000003e0dfc  /data/app/~~FRx4oZtvxOdKDK8iXc5cjw==/com.nextcloud.talk2-S2k0HXUo_FoaiHlotoj9sA==/base.apk!libjingle_peerconnection_so.so (BuildId: 234e35823a23d295)
      #04 pc 00000000003e0d0c  /data/app/~~FRx4oZtvxOdKDK8iXc5cjw==/com.nextcloud.talk2-S2k0HXUo_FoaiHlotoj9sA==/base.apk!libjingle_peerconnection_so.so (BuildId: 234e35823a23d295)
      #05 pc 00000000005c82f4  /data/app/~~FRx4oZtvxOdKDK8iXc5cjw==/com.nextcloud.talk2-S2k0HXUo_FoaiHlotoj9sA==/base.apk!libjingle_peerconnection_so.so (BuildId: 234e35823a23d295)
      #06 pc 00000000008d76b4  /data/app/~~FRx4oZtvxOdKDK8iXc5cjw==/com.nextcloud.talk2-S2k0HXUo_FoaiHlotoj9sA==/base.apk!libjingle_peerconnection_so.so (BuildId: 234e35823a23d295)
      #07 pc 00000000008d9aac  /data/app/~~FRx4oZtvxOdKDK8iXc5cjw==/com.nextcloud.talk2-S2k0HXUo_FoaiHlotoj9sA==/base.apk!libjingle_peerconnection_so.so (BuildId: 234e35823a23d295)
      #08 pc 00000000008d935c  /data/app/~~FRx4oZtvxOdKDK8iXc5cjw==/com.nextcloud.talk2-S2k0HXUo_FoaiHlotoj9sA==/base.apk!libjingle_peerconnection_so.so (BuildId: 234e35823a23d295)
      #09 pc 00000000008ceddc  /data/app/~~FRx4oZtvxOdKDK8iXc5cjw==/com.nextcloud.talk2-S2k0HXUo_FoaiHlotoj9sA==/base.apk!libjingle_peerconnection_so.so (BuildId: 234e35823a23d295)
      #10 pc 00000000007fa094  /data/app/~~FRx4oZtvxOdKDK8iXc5cjw==/com.nextcloud.talk2-S2k0HXUo_FoaiHlotoj9sA==/base.apk!libjingle_peerconnection_so.so (BuildId: 234e35823a23d295)
      #11 pc 00000000007fbbe4  /data/app/~~FRx4oZtvxOdKDK8iXc5cjw==/com.nextcloud.talk2-S2k0HXUo_FoaiHlotoj9sA==/base.apk!libjingle_peerconnection_so.so (BuildId: 234e35823a23d295)
      #12 pc 00000000007fa8e0  /data/app/~~FRx4oZtvxOdKDK8iXc5cjw==/com.nextcloud.talk2-S2k0HXUo_FoaiHlotoj9sA==/base.apk!libjingle_peerconnection_so.so (BuildId: 234e35823a23d295)
      #13 pc 000000000041d3e4  /data/app/~~FRx4oZtvxOdKDK8iXc5cjw==/com.nextcloud.talk2-S2k0HXUo_FoaiHlotoj9sA==/base.apk!libjingle_peerconnection_so.so (BuildId: 234e35823a23d295)
      #14 pc 000000000041d2cc  /data/app/~~FRx4oZtvxOdKDK8iXc5cjw==/com.nextcloud.talk2-S2k0HXUo_FoaiHlotoj9sA==/base.apk!libjingle_peerconnection_so.so (BuildId: 234e35823a23d295)
      #15 pc 00000000000f5548  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+208) (BuildId: 2bb0d7188c0db2e8beecb24658ba9d71)
      #16 pc 000000000008ef3c  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+68) (BuildId: 2bb0d7188c0db2e8beecb24658ba9d71)

```

**Comment by Doraemon-byte** [comment]
@mahibi Other phone models that crashed during video calls were: Oneplus 8T (Android 13), VIVO IQOO Neo 855 version (Android 11), Mi 12Pro (Android 13), because these devices do not belong to me, I have no way to get the crash log, I think that the crash of the mobile phone brand is not only the above few, it is possible that most other brands of mobile phones in China should also have the problem

**Comment by mahibi** [comment]
good to know, thanks for sharing @Doraemon-byte !

**Comment by Doraemon-byte** [comment]
@mahibi Hello, Has there been any progress on this issue?

**Comment by Doraemon-byte** [comment]
> 很高兴知道，谢谢分享！



> good to know, thanks for sharing @Doraemon-byte !

@mahibi Good day, could you please let me know if there are any plans to investigate this issue in the future?

**Comment by mahibi** [comment]
Hi @Doraemon-byte 
it will be addressed whenever time allows, which is not currently the case.

**Comment by Doraemon-byte** [comment]
Hello, I am now sending a new crash log for your subsequent analysis.
```

Redmi/alioth/alioth:13/TKQ1.220829.002/V14.0.8.0.TKHCNXM:user/release-keys

      #00 pc 000000000008d6f4  /apex/com.android.runtime/lib64/bionic/libc.so (abort+168) (BuildId: 2bb0d7188c0db2e8beecb24658ba9d71)
      #01 pc 00000000003fe5c0  /data/app/~~7czLwhMPzsw5jwISJ6Hi4w==/com.nextcloud.talk2-CLc0inWjD6XKuYUNUZckQw==/base.apk!libjingle_peerconnection_so.so (BuildId: 234e35823a23d295)
      #02 pc 00000000003fec0c  /data/app/~~7czLwhMPzsw5jwISJ6Hi4w==/com.nextcloud.talk2-CLc0inWjD6XKuYUNUZckQw==/base.apk!libjingle_peerconnection_so.so (BuildId: 234e35823a23d295)
      #03 pc 00000000003e0dfc  /data/app/~~7czLwhMPzsw5jwISJ6Hi4w==/com.nextcloud.talk2-CLc0inWjD6XKuYUNUZckQw==/base.apk!libjingle_peerconnection_so.so (BuildId: 234e35823a23d295)
      #04 pc 00000000003e0d0c  /data/app/~~7czLwhMPzsw5jwISJ6Hi4w==/com.nextcloud.talk2-CLc0inWjD6XKuYUNUZckQw==/base.apk!libjingle_peerconnection_so.so (BuildId: 234e35823a23d295)
      #05 pc 00000000005c6420  /data/app/~~7czLwhMPzsw5jwISJ6Hi4w==/com.nextcloud.talk2-CLc0inWjD6XKuYUNUZckQw==/base.apk!libjingle_peerconnection_so.so (BuildId: 234e35823a23d295)
      #06 pc 00000000005cbad4  /data/app/~~7czLwhMPzsw5jwISJ6Hi4w==/com.nextcloud.talk2-CLc0inWjD6XKuYUNUZckQw==/base.apk!libjingle_peerconnection_so.so (BuildId: 234e35823a23d295)
      #07 pc 00000000008a671c  /data/app/~~7czLwhMPzsw5jwISJ6Hi4w==/com.nextcloud.talk2-CLc0inWjD6XKuYUNUZckQw==/base.apk!libjingle_peerconnection_so.so (BuildId: 234e35823a23d295)
      #08 pc 00000000008a4afc  /data/app/~~7czLwhMPzsw5jwISJ6Hi4w==/com.nextcloud.talk2-CLc0inWjD6XKuYUNUZckQw==/base.apk!libjingle_peerconnection_so.so (BuildId: 234e35823a23d295)
      #09 pc 00000000008a49dc  /data/app/~~7czLwhMPzsw5jwISJ6Hi4w==/com.nextcloud.talk2-CLc0inWjD6XKuYUNUZckQw==/base.apk!libjingle_peerconnection_so.so (BuildId: 234e35823a23d295)
      #10 pc 00000000008af4dc  /data/app/~~7czLwhMPzsw5jwISJ6Hi4w==/com.nextcloud.talk2-CLc0inWjD6XKuYUNUZckQw==/base.apk!libjingle_peerconnection_so.so (BuildId: 234e35823a23d295)
      #11 pc 00000000008ca254  /data/app/~~7czLwhMPzsw5jwISJ6Hi4w==/com.nextcloud.talk2-CLc0inWjD6XKuYUNUZckQw==/base.apk!libjingle_peerconnection_so.so (BuildId: 234e35823a23d295)
      #12 pc 00000000008ca0dc  /data/app/~~7czLwhMPzsw5jwISJ6Hi4w==/com.nextcloud.talk2-CLc0inWjD6XKuYUNUZckQw==/base.apk!libjingle_peerconnection_so.so (BuildId: 234e35823a23d295)
      #13 pc 00000000008caaf8  /data/app/~~7czLwhMPzsw5jwISJ6Hi4w==/com.nextcloud.talk2-CLc0inWjD6XKuYUNUZckQw==/base.apk!libjingle_peerconnection_so.so (BuildId: 234e35823a23d295)
      #14 pc 00000000007fa094  /data/app/~~7czLwhMPzsw5jwISJ6Hi4w==/com.nextcloud.talk2-CLc0inWjD6XKuYUNUZckQw==/base.apk!libjingle_peerconnection_so.so (BuildId: 234e35823a23d295)
      #15 pc 00000000007fbbe4  /data/app/~~7czLwhMPzsw5jwISJ6Hi4w==/com.nextcloud.talk2-CLc0inWjD6XKuYUNUZckQw==/base.apk!libjingle_peerconnection_so.so (BuildId: 234e35823a23d295)
      #16 pc 00000000007fa8e0  /data/app/~~7czLwhMPzsw5jwISJ6Hi4w==/com.nextcloud.talk2-CLc0inWjD6XKuYUNUZckQw==/base.apk!libjingle_peerconnection_so.so (BuildId: 234e35823a23d295)
      #17 pc 000000000041d3e4  /data/app/~~7czLwhMPzsw5jwISJ6Hi4w==/com.nextcloud.talk2-CLc0inWjD6XKuYUNUZckQw==/base.apk!libjingle_peerconnection_so.so (BuildId: 234e35823a23d295)
      #18 pc 000000000041d2cc  /data/app/~~7czLwhMPzsw5jwISJ6Hi4w==/com.nextcloud.talk2-CLc0inWjD6XKuYUNUZckQw==/base.apk!libjingle_peerconnection_so.so (BuildId: 234e35823a23d295)
      #19 pc 00000000000f5548  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+208) (BuildId: 2bb0d7188c0db2e8beecb24658ba9d71)
      #20 pc 000000000008ef3c  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+68) (BuildId: 2bb0d7188c0db2e8beecb24658ba9d71)

```

**Comment by lsq286224380** [comment]
请问有进展吗？多名用户视频聊天遇到了相同的问题

**Comment by redfearnk** [comment]
I am seeing this crash on Samsung devices

**Comment by mahibi** [comment]
This finally needs to be investigated as there are too many crash reports for this on gplay.

logs from gplay:

```
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 2609 >>> com.nextcloud.talk2 <<<

backtrace:
  #00  pc 0x00000000000940a4  /apex/com.android.runtime/lib64/bionic/libc.so (abort+164)
  #01  pc 0x000000000042792c  /data/app/~~2Fl0foXdHtHyDFvECHZ74A==/com.nextcloud.talk2-Ba1s0xEcqhcEiuU0x5c_Lw==/base.apk!libjingle_peerconnection_so.so (BuildId: 9f0b974988196db9)
  #02  pc 0x0000000000427f78  /data/app/~~2Fl0foXdHtHyDFvECHZ74A==/com.nextcloud.talk2-Ba1s0xEcqhcEiuU0x5c_Lw==/base.apk!libjingle_peerconnection_so.so (BuildId: 9f0b974988196db9)
  #03  pc 0x0000000000417654  /data/app/~~2Fl0foXdHtHyDFvECHZ74A==/com.nextcloud.talk2-Ba1s0xEcqhcEiuU0x5c_Lw==/base.apk!libjingle_peerconnection_so.so (BuildId: 9f0b974988196db9)
  #04  pc 0x0000000000417564  /data/app/~~2Fl0foXdHtHyDFvECHZ74A==/com.nextcloud.talk2-Ba1s0xEcqhcEiuU0x5c_Lw==/base.apk!libjingle_peerconnection_so.so (BuildId: 9f0b974988196db9)
  #05  pc 0x0000000000830de8  /data/app/~~2Fl0foXdHtHyDFvECHZ74A==/com.nextcloud.talk2-Ba1s0xEcqhcEiuU0x5c_Lw==/base.apk!libjingle_peerconnection_so.so (BuildId: 9f0b974988196db9)
  #06  pc 0x0000000000433110  /data/app/~~2Fl0foXdHtHyDFvECHZ74A==/com.nextcloud.talk2-Ba1s0xEcqhcEiuU0x5c_Lw==/base.apk!libjingle_peerconnection_so.so (BuildId: 9f0b974988196db9)
  #07  pc 0x00000000004325b8  /data/app/~~2Fl0foXdHtHyDFvECHZ74A==/com.nextcloud.talk2-Ba1s0xEcqhcEiuU0x5c_Lw==/base.apk!libjingle_peerconnection_so.so (BuildId: 9f0b974988196db9)
  #08  pc 0x0000000000433498  /data/app/~~2Fl0foXdHtHyDFvECHZ74A==/com.nextcloud.talk2-Ba1s0xEcqhcEiuU0x5c_Lw==/base.apk!libjingle_peerconnection_so.so (BuildId: 9f0b974988196db9)
  #09  pc 0x0000000000101b9c  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+204)
  #10  pc 0x0000000000095a00  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64)
```

**Comment by redfearnk** [comment]
I learned this crash only happened to me when there were more than 16 concurrent peer connections, with 16 concurrent TextureViews rendering video. Limiting the number of players resolved the issue for me, which might not be an option for everyone. I have the option of falling back to an RTSP stream
