### ISSUE TITLE
Funny 2 characters long pattern specific search crash 

### ISSUE THREAD

**Issue by YoannPa** [nextcloud/talk-android#3194]
### Steps to reproduce

I guess this is the funniest crash I experienced so far in Nextcloud Talk.
When searching for a conversation in the app, if I slowly type "aa", "pa", "ma" (lower case or upper case, or mixed lower and upper case) the search instantly crashes the app, and the app reloads itself to bring me back to the conversations list.

And you have to type this slowly. because if you type it fast enough, adding more characters after these 2, the search will not lead to a crash.
For example: typing quickly "aaf" or "pap" or "mae" will perfectly work, and shortlist conversations containing these strings.

I haven't tried all 2 characters possible combinations leading to a crash obviously, but found these 3 ("aa", "pa", "ma") at least.

### Expected behaviour

Conversation search should not specifically crash for 2 characters strings such as "aa", "pa", "ma", and shoudl shortlist the conversations matching these strings.

### Actual behaviour

When typing specifically these 2 characters strings "aa", "pa", "ma", the nextcloud talk app crashes.

Crashes can happen following 2 different displays:
- Case n°1: this screen will show up for a second before bringing back the user to the conversations list.
![Screenshot_20230717-030645](https://github.com/nextcloud/talk-android/assets/12813932/418298d1-afc8-4e6f-9dd9-e93ee8e266d7)
- Case n°2: this usually happens after several search crashes (one of the problematic string is even visible in the search field on this picture).
![Screenshot_20230717-030407](https://github.com/nextcloud/talk-android/assets/12813932/fe2824ce-e11a-4729-b10c-7f68e9ae0c63)

### Device brand and model

Fairphone 4

### Android version

12

### Nextcloud Talk app version

v17.0.1

### Nextcloud server version

26.0.3

### Talk version

16.0.4

### Custom Signaling server configured

None

### Custom TURN server configured

None

### Custom STUN server configured

None

**Comment by mahibi** [comment]
i can reproduce this and get this exeception:
```

2023-07-17 10:07:00.963  4629-4629  AndroidRuntime          com.nextcloud.talk2                  E  FATAL EXCEPTION: main
                                                                                                    Process: com.nextcloud.talk2, PID: 4629
                                                                                                    java.lang.IndexOutOfBoundsException: setSpan (-1 ... 6) starts before 0
                                                                                                    	at android.text.SpannableStringInternal.checkRange(SpannableStringInternal.java:499)
                                                                                                    	at android.text.SpannableStringInternal.setSpan(SpannableStringInternal.java:199)
                                                                                                    	at android.text.SpannableStringInternal.setSpan(SpannableStringInternal.java:186)
                                                                                                    	at android.text.SpannableString.setSpan(SpannableString.java:60)
                                                                                                    	at com.nextcloud.android.common.ui.theme.utils.AndroidViewThemeUtils.spanText(AndroidViewThemeUtils.kt:584)
                                                                                                    	at com.nextcloud.android.common.ui.theme.utils.AndroidViewThemeUtils.highlightText(AndroidViewThemeUtils.kt:562)
                                                                                                    	at com.nextcloud.android.common.ui.theme.utils.AndroidViewThemeUtils.access$highlightText(AndroidViewThemeUtils.kt:75)
                                                                                                    	at com.nextcloud.android.common.ui.theme.utils.AndroidViewThemeUtils$highlightText$1.invoke(AndroidViewThemeUtils.kt:548)
                                                                                                    	at com.nextcloud.android.common.ui.theme.utils.AndroidViewThemeUtils$highlightText$1.invoke(AndroidViewThemeUtils.kt:547)
                                                                                                    	at com.nextcloud.android.common.ui.theme.ViewThemeUtilsBase.withScheme(ViewThemeUtilsBase.kt:49)
                                                                                                    	at com.nextcloud.android.common.ui.theme.utils.AndroidViewThemeUtils.highlightText(AndroidViewThemeUtils.kt:547)
                                                                                                    	at com.nextcloud.android.common.ui.theme.utils.AndroidViewThemeUtils.highlightText$default(AndroidViewThemeUtils.kt:541)
                                                                                                    	at com.nextcloud.talk.adapters.items.ConversationItem.bindViewHolder(ConversationItem.kt:122)
                                                                                                    	at com.nextcloud.talk.adapters.items.ConversationItem.bindViewHolder(ConversationItem.kt:61)
                                                                                                    	at eu.davidea.flexibleadapter.FlexibleAdapter.onBindViewHolder(FlexibleAdapter.java:1772)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7761)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6582)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6848)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6688)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6684)
                                                                                                    	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2362)
                                                                                                    	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1662)
                                                                                                    	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1622)
                                                                                                    	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:687)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:4550)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4305)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:2065)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView$1.run(RecyclerView.java:438)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1301)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1309)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:923)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:847)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1283)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8757)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

somehow the index in
`/home/marcel/.gradle/caches/modules-2/files-2.1/com.github.nextcloud.android-common/ui/0.11.0/f4838637da1b29ac80f0ff46b020871002eb3b30/ui-0.11.0-sources.jar!/com/nextcloud/android/common/ui/theme/utils/AndroidViewThemeUtils.kt:586`

becomes -1 which leads to IndexOutOfBoundsException.

So this is related to the feature to hightlight parts of the conversations with the entered string.
Which letters lead to the crash will most likely depend on the conversation names, so i guess it's different for each instance.
For example "aa" also crashed on the instance that i used (sermo), which contains a conversation called "AAAAAA".

i will have a closer look later
