### ISSUE TITLE
crash when tapping on microphone button in chat

### ISSUE THREAD

**Issue by mahibi** [nextcloud/talk-android#3265]
### Steps to reproduce

tap on microphone button in chat (don't hold)

### Expected behaviour

info pops up: "Hold to record, release to send."

### Actual behaviour

app crash

```
2023-08-23 10:47:22.483 29928-29928 Toast                   com.nextcloud.talk2                  V  show: caller = com.nextcloud.talk.chat.ChatActivity$initVoiceRecordButton$7.onTouch:1173 
2023-08-23 10:47:22.487 29928-29928 MediaRecorderJNI        com.nextcloud.talk2                  I  stop
2023-08-23 10:47:22.772 29928-29928 MediaRecorder           com.nextcloud.talk2                  E  stop failed: -1007
2023-08-23 10:47:22.773 29928-29928 InputEventReceiver      com.nextcloud.talk2                  E  Exception dispatching input event.
2023-08-23 10:47:22.773 29928-29928 MessageQueue-JNI        com.nextcloud.talk2                  E  Exception in MessageQueue callback: handleReceiveCallback
2023-08-23 10:47:22.778 29928-29928 MessageQueue-JNI        com.nextcloud.talk2                  E  java.lang.RuntimeException: stop failed.
                                                                                                    	at android.media.MediaRecorder._stop(Native Method)
                                                                                                    	at android.media.MediaRecorder.stop(MediaRecorder.java:1702)
                                                                                                    	at com.nextcloud.talk.chat.ChatActivity.stopAudioRecording(ChatActivity.kt:2112)
                                                                                                    	at com.nextcloud.talk.chat.ChatActivity.stopAndDiscardAudioRecording(ChatActivity.kt:2098)
                                                                                                    	at com.nextcloud.talk.chat.ChatActivity.access$stopAndDiscardAudioRecording(ChatActivity.kt:256)
                                                                                                    	at com.nextcloud.talk.chat.ChatActivity$initVoiceRecordButton$7.onTouch(ChatActivity.kt:1174)
                                                                                                    	at android.view.View.dispatchTouchEvent(View.java:15540)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3316)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2990)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3316)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2990)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3316)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2990)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3316)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2990)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3316)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2990)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3316)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2990)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3316)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2990)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3316)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2990)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3316)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2990)
                                                                                                    	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:1112)
                                                                                                    	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1971)
                                                                                                    	at android.app.Activity.dispatchTouchEvent(Activity.java:4388)
                                                                                                    	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:70)
                                                                                                    	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:1070)
                                                                                                    	at android.view.View.dispatchPointerEvent(View.java:15803)
                                                                                                    	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:8153)
                                                                                                    	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7877)
                                                                                                    	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7213)
                                                                                                    	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7270)
                                                                                                    	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:7236)
                                                                                                    	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7434)
                                                                                                    	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:7244)
                                                                                                    	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:7491)
                                                                                                    	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7217)
                                                                                                    	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7270)
                                                                                                    	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:7236)
                                                                                                    	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:7244)
                                                                                                    	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7217)
                                                                                                    	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:10788)
                                                                                                    	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:10676)
                                                                                                    	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:10632)
                                                                                                    	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:10926)
                                                                                                    	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:285)
                                                                                                    	at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                                                    	at android.os.MessageQueue.next(MessageQueue.java:335)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:186)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
2023-08-23 10:47:22.778 29928-29928 MessageQueue-JNI        com.nextcloud.talk2                  E  	at android.app.ActivityThread.main(ActivityThread.java:8757)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
2023-08-23 10:47:22.778 29928-29928 AndroidRuntime          com.nextcloud.talk2                  D  Shutting down VM
```

### Device brand and model

.

### Android version

.

### Nextcloud Talk app version

17.10.0 Alpha 17

### Custom Signaling server configured

None

### Custom TURN server configured

None

### Custom STUN server configured

None

**Comment by mahibi** [comment]
@rapterjet2004 can you have a look? most probably a bug from https://github.com/nextcloud/talk-android/pull/3135

**Comment by rapterjet2004** [comment]
oh that's not good, I'll get to it.

**Comment by mahibi** [comment]
yes handling the mediaRecorder is a challenge and you quickly have exceptions. it's a pity that it's not a bit more robust.
