### ISSUE TITLE
IOB when entering certains talk room

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/talk-android#4045]
### Steps to reproduce

1. enter certain talk rooms (with edited messages it seems from the stack trace)
2. crash returning you to conversation list

### Expected behaviour

no crash, conversation opened/rendered

### Actual behaviour

crash with an index out of bounds

### Device brand and model

OP9T

### Android version

14

### Nextcloud Talk app version

20-pre-release

### Nextcloud server version

30.0.0beta3

### Talk version

20

### Custom Signaling server configured

Yes (specify version in Additional Information)

### Custom TURN server configured

None

### Custom STUN server configured

None

### Android logs

io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 0
at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:126)
at android.os.Handler.handleCallback(Handler.java:958)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:257)
at android.os.Looper.loop(Looper.java:368)
at android.app.ActivityThread.main(ActivityThread.java:8839)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
  Caused by: java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 0
at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
at java.util.Objects.checkIndex(Objects.java:359)
at java.util.ArrayList.get(ArrayList.java:434)
at com.nextcloud.talk.chat.ChatActivity.setMessageAsEdited(ChatActivity.kt:3388)
at com.nextcloud.talk.chat.ChatActivity.handleSystemMessages(ChatActivity.kt:2957)
at com.nextcloud.talk.chat.ChatActivity.initObservers$lambda$22(ChatActivity.kt:766)
at com.nextcloud.talk.chat.ChatActivity.$r8$lambda$oL-e6FrOeroB4GQnw2pZ_VkwoeQ(Unknown Source:0)
at com.nextcloud.talk.chat.ChatActivity$$ExternalSyntheticLambda47.invoke(D8$$SyntheticClass:0)
at com.nextcloud.talk.chat.ChatActivity$sam$androidx_lifecycle_Observer$0.onChanged(Unknown Source:2)
at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
at com.nextcloud.talk.chat.viewmodels.ChatViewModel$pullChatMessages$2.onNext(ChatViewModel.kt:394)
at com.nextcloud.talk.chat.viewmodels.ChatViewModel$pullChatMessages$2.onNext(ChatViewModel.kt:376)
at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:124)
at android.os.Handler.handleCallback(Handler.java:958)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:257)
at android.os.Looper.loop(Looper.java:368)
at android.app.ActivityThread.main(ActivityThread.java:8839)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)

**Comment by AndyScherzinger** [comment]
deployed latest master, not happening at the moment anymore... So I close it for the moment until it might happen again
