### ISSUE TITLE
Pixel 3a Android 10 crash on (latest) app launch

### ISSUE THREAD

**Issue by bobreidx** [nextcloud/talk-android#642]
Since installing the update, the app constantly crashes when launched on a Pixel 3a running Android 10. Coincidentally, the Play Store installed app cache is now also corrupt, and shows no apps installed on my phone. I have done everything short of reset the phone, and the app is now uninstalled until it gets updated again.

**Comment by bobreidx** [comment]
Play Store issue resolved with resetting the Play Store app cache and restarting the app.

**Comment by mario** [comment]
So the app now works as expected or still not?

**Comment by bobreidx** [comment]
I haven't reinstalled the Talk app yet

**Comment by bobreidx** [comment]
After a complete app reinstall, the app now launches and sets up fine, but always crashes when attempting to open a conversation thread. The contact name in the thread header quickly changes to "null" right before the crash.

**Comment by mario** [comment]
What Nc version?

**Comment by bobreidx** [comment]
16.0.4

sent from mobile

________________________________

**Comment by mario** [comment]
Mind sending test account to mario@nextcloud.com?

**Comment by steinhuber** [comment]
Same on my Xiaomi Mi 9(MiMu Global 10).I geht this exception:
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.nextcloud.talk.models.json.conversations.Conversation$ConversationType.equals(java.lang.Object)' on a null object reference
	at com.nextcloud.talk.controllers.ChatController.processMessages(ChatController.java:1126)
	at com.nextcloud.talk.controllers.ChatController.access$3300(ChatController.java:156)
	at com.nextcloud.talk.controllers.ChatController$16.onNext(ChatController.java:1056)
	at com.nextcloud.talk.controllers.ChatController$16.onNext(ChatController.java:1048)
	at io.reactivex.internal.operators.observable.ObservableTakeWhile$TakeWhileObserver.onNext(ObservableTakeWhile.java:88)
	at io.reactivex.internal.operators.observable.ObservableRetryPredicate$RepeatObserver.onNext(ObservableRetryPredicate.java:69)
	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
	at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:124)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6815)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by bobreidx** [comment]
Unable to contact admin so far.

sent from mobile

________________________________

**Comment by mario** [comment]
All good, I'm working on the issues already!

**Comment by bobreidx** [comment]
Unfortunately, app version 7.0.2 still crashes intermittently, and now has to re-download an entire message thread (previously the app would cache the thread) before trying to function. I have uninstalled, and filing a new issue.

**Comment by mario** [comment]
I don't see a crash at the play console I am afraid :( did you submit it?

**Comment by steinhuber** [comment]
I had the same problem. Solved it by updating nc to 17.0.0 RC and talk to 7.0.0.
