### ISSUE TITLE
App crashes on shutdown

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/talk-android#707]
**Sometimes** when the application is turned off, an app crash occurs.

Steps:

1. Receiving a new message.
2. Read the message by push notification.
3. Close the app.
4. **Sometimes** the application crashes.

App:
Android 6
Android Talk 7.0.8 and v8.0.0beta3

Below the stack trace from the system:
```
2020-01-15 14:05:43 data_app_crash (text, 1361 bytes)
    Process: com.nextcloud.talk2/Flags: 0x38d8be44/Package: com.nextcloud. ...
```
```
01-15 14:05:43.796  8538  8538 E AndroidRuntime: FATAL EXCEPTION: main
01-15 14:05:43.796  8538  8538 E AndroidRuntime: Process: com.nextcloud.talk2, PID: 8538
01-15 14:05:43.796  8538  8538 E AndroidRuntime: kotlin.KotlinNullPointerException
01-15 14:05:43.796  8538  8538 E AndroidRuntime: 	at com.nextcloud.talk.controllers.ChatController.setupMentionAutocomplete(ChatController.kt:561)
01-15 14:05:43.796  8538  8538 E AndroidRuntime: 	at com.nextcloud.talk.controllers.ChatController.access$setupMentionAutocomplete(ChatController.kt:116)
01-15 14:05:43.796  8538  8538 E AndroidRuntime: 	at com.nextcloud.talk.controllers.ChatController$getRoomInfo$1.onNext(ChatController.kt:245)
01-15 14:05:43.796  8538  8538 E AndroidRuntime: 	at com.nextcloud.talk.controllers.ChatController$getRoomInfo$1.onNext(ChatController.kt:235)
01-15 14:05:43.796  8538  8538 E AndroidRuntime: 	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
01-15 14:05:43.796  8538  8538 E AndroidRuntime: 	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
01-15 14:05:43.796  8538  8538 E AndroidRuntime: 	at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:124)
01-15 14:05:43.796  8538  8538 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
01-15 14:05:43.796  8538  8538 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
01-15 14:05:43.796  8538  8538 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
01-15 14:05:43.796  8538  8538 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5530)
01-15 14:05:43.796  8538  8538 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-15 14:05:43.796  8538  8538 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:734)
01-15 14:05:43.796  8538  8538 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:624)
```

**Comment by mario** [comment]
Beta4.
