### ISSUE TITLE
Firebase Exception when receiving new messages

### ISSUE THREAD

**Issue by Quaks** [nextcloud/talk-android#745]
The Android App throws an exception when receiving new messages caused of Google FCM.

Exception Trace: 

************ CAUSE OF ERROR ************

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/analytics/connector/AnalyticsConnector;
at com.google.firebase.messaging.MessagingAnalytics.zza(Unknown Source:68)
at com.google.firebase.messaging.MessagingAnalytics.logNotificationReceived(Unknown Source:2)
at com.google.firebase.messaging.FirebaseMessagingService.zzd(Unknown Source:50)
at com.google.firebase.iid.zzg.run(Unknown Source:4)
at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:7)
at java.lang.Thread.run(Thread.java:784)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.analytics.connector.AnalyticsConnector" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.nextcloud.client-9Ua0vemtO0eoNfqqG-sACA==/base.apk"],nativeLibraryDirectories=[/data/app/com.nextcloud.client-9Ua0vemtO0eoNfqqG-sACA==/lib/arm64, /data/app/com.nextcloud.client-9Ua0vemtO0eoNfqqG-sACA==/base.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
... 9 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30100190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: HUAWEI
Device: HWELE
Model: ELE-L29
Id: HUAWEIELE-L29
Product: ELE-L29EEA

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 9.1.0.240C431

**Comment by mario** [comment]
Uh uh uh. Sounds like same issue as https://github.com/nextcloud/android/issues/4675 - cause is unknown for now.

**Comment by mario** [comment]
Bug in the Google code. Will be fixed in one of the upcoming version.

**Comment by tobiasKaminsky** [comment]
Do you have a link? So I could post this also on our files issue?

**Comment by mario** [comment]
Not from Google, no. But I already posted the info on how to fix there.

**Comment by mario** [comment]
Should be fixed today.
